### ISSUE TITLE
Switch authentication to silhouette instead of unmaintained securesocial

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#1194]
The `securesocial` library we are using for authentication is not maintained any more. Hence, we need to switch to the silhouette library instead (good decision anyway since it allows us to get rid of the last few necessary backend templates).

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1194/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
@tmbo @jfrohnhofen Do you think it makes sense to update to `silhouette` before updating to Play 2.6? Silhouette 3.0 is compatible with Play 2.4: https://www.silhouette.rocks/docs/releases

This could something that @rschwanhold could look into.

**Comment by tmbo** [comment]
Sounds like a great idea, like it :+1:

**Comment by jfrohnhofen** [comment]
@hotzenklotz 
@rschwanhold, @normanrz and I talked about how this issue might be a good opportunity to get rid of some more scala templates by replacing the login/signup process with a JSON api. What do you think? Can you have a look at the frontend parts of this once you are back?

**Comment by hotzenklotz** [comment]
@rschwanhold It looks like the Jenkins builds fail because the frontend end-to-end test fail. 

```Unhandled Rejection: public/test-bundle/test/enzyme/snapshot.e2e.js
  SyntaxError: Unexpected token < in JSON at position 5
    JSON.parse (<anonymous>)
    response.text.then.responseText (public/test-bundle/libs/request.js:221:21)
    <anonymous>
```
It looks like some requests to the server don't return valid JSON. Judging by the token `<` HTML is returned as a response. What causes the server to return HTML? A redirect?
Perhaps the user is not logged in during the execution of the tests.

**Comment by jfrohnhofen** [comment]
I discussed adding token-based authentication next to cookie-based authentication with @rschwanhold and @hotzenklotz today. Silhouette does not provide any mechanism to use two authentication methods at the same time, we could implement our own, that dispatches betewwn the two existing authentication modes (cookie and token). While this should work, I am not sure, whether this is worthwhile doing, since both authentication mechanisms are pretty similar. if we persist the cookies and have them never  expire, they are essentially tokens and it should not really matter for API users, if we require them to add a `X-Auth-Token` header vs a cookie header. Your opinion?

**Comment by jfrohnhofen** [comment]
@normanrz ^^

**Comment by normanrz** [comment]
I think there is some value in having two separate auth mechanisms. 1. I think it would be good to go with convention and have cookie and token separated. Otherwise it will confuse people. 2. Isn't a cookie destroyed upon logout? This should be independent of the tokens, which are expected to last much longer.
