### ISSUE TITLE
Spotlight for not logged in people should only show the view option

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#1270]
Right now all three buttons (view, trace, volume) are shown on datasets on the dashboard. But as a user that is not logged in one is only able to use view. Hence, the other two should be hidden.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1270/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
When clicking on the skeleton or volume tracing buttons, this message is displayed: "For dataset annotation, please log in or create an account. For dataset viewing, no account is required.
Do you wish to sign up now?", which redirects to the signup page if the user clicks ok. I'm closing this issue because I think this is fine, please reopen if you disagree.
