### ISSUE TITLE
Configuration setting to disable internal datastore

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#1561]
For docker setup it would be helpful to disable the integrated datastore, so that people cannot upload datasets to the ephemeral storage.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1561/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
this can be done by removing `play.modules.enabled += "com.scalableminds.braingames.datastore.DataStoreModule"` from the config

**Comment by normanrz** [comment]
Is `play.modules.enabled -= "com.scalableminds.braingames.datastore.DataStoreModule"` also possible (because we derive from `application.conf`)?

**Comment by jfrohnhofen** [comment]
@normanrz Unfortunately this is not as easy as I thought. Simply disabling the module as I suggested above will not work, since the play router will still try to serve the datastore routes and crash the server, since it cannot find most of the stuff it needs to do so (since the module is not available).

I think there are two possible approaches here:
1) **disable the module and disable the routes**
This is the cleaner way, since in that case the dataStore really does not exist anymore (i.e. no rocksDB is created etc.) The downside is, that we need to have a second routes file on the server (one with the datastore routes and one without), which need to be kept in sync. The routes file can then be selected fron the config.

2) **filter requests to the datastore**
The second option is to create an `HttpFilter`, that filters all requests with a `/data/` prefix. While that would block the access to the dataStore routes for the client, the dataStore itself is still running and there is no single point of code to prevent that. Instead we would have to read some `datastore.enabled` flag in a few different places, where the dataStore does stuff (e.g. dataSource discovery, ...)

I would prefer the first option, if we find a good solution to the routes file problem

**Comment by normanrz** [comment]
A couple of ideas that may or may not make sense:
* Is it possible to import a routes file in another routes file? Perhaps we could concat them in sbt
* Or could we have a separate instance of the play router for the datastore requests? The webknossos router could then forward all requests by a catch-all handler on `/data/*`.
