### ISSUE TITLE
Prevent special user from deactivating

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#1638]
For demo instance it would be bad if people would deactivate the Demo user account that is the auto-login user.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1638/create?referer=github" target="_blank">Log Time</a>

**Comment by rschwanhold** [comment]
@normanrz The admin can deactivate other users. Is there a way to deactivate or delete his own account without beeing an admin? If not, is this issue still necessary? Because if the Demo account is not an admin, it could not get deleted or deactivated in the first place (while being logged in as this demo account)
In case the issue is still relevant:
Every user now has the flag `isProtected`. The default is `isProtected = false`. How should it be possible to change that flag? Should there be an option so that the user can change his own flag  (or should only admins have the option to change the flag of other users)? Or is this feature so rarely used that it would be sufficient to change the flag directly in the DB? 
Another question:
The only way to deactivate a user is with the `update` method in `UserService`. This methode updates multiple attributes at once. In case the user `isProtected = true`, should the other attributes get updated or should the update get rejected and a message pop up, like "This user is protected from deactivation"?

**Comment by normanrz** [comment]
I think this issue is no longer relevant. Back then, we wanted to have an auto-admin feature that would make all new users admins. Therefore, they could possibly deactivate the demo admin user which would be bad. But then we decided against using the auto-admin feature making this issue irrelevant.

**Comment by normanrz** [comment]
But thanks for looking into this :+1: and sorry for not closing this issue sooner :-(
