### ISSUE TITLE
Store skeletons as JSON in RocksDB

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#1759]
The way skeleton tracings are currently stored in mongoDB does not scale to >200.000 nodes and must thus be stored in a different way.

- [ ] move skeleton tracings to datastore
- [ ] move skeleton tracing format to JSON
- [ ] save skeleton modifications to write-log
- [ ] apply skeleton modifications on skeleton requests
- [ ] authentication via tokens
- [ ] validate skeleton schema (and find/define NML schema) (see https://discuss.webknossos.org/t/backend-validation-of-skeletons/122)
- [ ] add support for skeleton versions (see https://discuss.webknossos.org/t/undo-user-actions/146)

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1759/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
related
https://discuss.webknossos.org/t/backend-validation-of-skeletons/122
https://discuss.webknossos.org/t/performance-issues-with-large-amounts-of-data/86

**Comment by daniel-wer** [comment]
@fm3 @jfrohnhofen I've made the changes in the frontend to fetch the annotation, dataset and tracing separately (and repaired all places in the frontend that were affected by that). There's still a couple of ToDos, which are being kept track of in the collabedit pad.
At least it's possible to create a skeletontracing now and look at the data. Volume tracings don't seem to work yet and there's a small error for Viewing tracings that I already mentioned to @fm3.

If I understood correctly, the update actions should now be sent to the dataStore instead of the server. Same route or did something change there?

**Comment by daniel-wer** [comment]
Just for reference, the relevant branch is `bravenewworldSkeletons`.
