### ISSUE TITLE
Compact "tree deletion" actions

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#1907]
Tree deletion results in a ton of "deleteNode" and "deleteEdge" actions upon saving. We should compact these similar to tree merges / splits.

I am unclear whether the backend supports a dedicated tree deletion action. Perhaps, @fm3 can comment on this.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1907/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
Since in the new version the skeleton tracing is saved as a case class instance (with a list of trees as a field) rather than mongo database entries, [this line](https://github.com/scalableminds/braingames-libs/blob/brave_new_world/braingames-datastore/app/com/scalableminds/braingames/datastore/tracings/skeleton/elements/SkeletonTracing.scala#L30) should already be enough to get rid of all the edges and nodes in that tree, meaning that if the deleteTree action comes first, subsequent deleteNode and deleteEdge actions are actually redundant and ignored.

**Comment by daniel-wer** [comment]
Yes I talked to @jfrohnhofen before and he assured me that even in the current version it's sufficient to send a deleteTree update action, without sending accompanying deleteNode/deleteEdge update actions. I'll add this enhancement to the frontend code.
