### ISSUE TITLE
Enhance "Explorative Annotations" list

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#1938]
This tab is the most important view for many researcher and hence should get some love:

- [x] Fuzzy search (name, dataset etc)
- [ ] Quicker loading speed
    - [x] through react
    - [ ] through rocksdb
- [x] Perhaps make it the default tab (confirm with other users first) / remember last tab
- [x] Reactify

See https://discuss.webknossos.org/t/show-multiple-tracings-at-once-workspaces/375/7?u=therold

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1938/create?referer=github" target="_blank">Log Time</a>

**Comment by daniel-wer** [comment]
Regarding the loading speed I did some quick measure using the Chrome Console Performance Tab:

For a user with 920 explorative tracings:
- Time-to-first-byte: 1.62s
- Download of the data: 87ms
- Rendering: 3.21s

Overall time: 4.8s

Rendering is mostly Backbones `addChildView`. I think there is definitely potential in switching to React for the rendering, but it should also be possible for the server to speed up the fetching of the explorative tracings. @jfrohnhofen will have a look if there is some low-hanging optimization potential there.

**Comment by normanrz** [comment]
Once we move the database to an SSD server the query speed should be much improved.

**Comment by jfrohnhofen** [comment]
@daniel-wer The loading speed should improve quite a bit, once we move the skeleton tracings to the datastore. But there is no easy way to speed it up right now.

**Comment by philippotto** [comment]
I rebuilt the datasets, the tasks and the explorative annotations views in react (not fully done yet but the big parts are ready). I did a new performance benchmark in which I just toggle "show unarchived tracings" so that 500 tracings will be shown:

Old dashboard:
- 6,5 seconds scripting + 1,5 seconds rendering

New dashboard:
- 0,4 seconds scripting + 0,1 seconds rendering

:tada: 

I wonder why @daniel-wer's times are way shorter. Were all 920 tracings rendered?

Regarding the default tab question, I built it so that the active tab will be remembered across reloads.
Fuzzy searching should be easy to achieve, but I'd like to get some details first. We should discuss how fuzzy things can get etc. (e.g., sublimes fuzzy matching is very loose).

**Comment by hotzenklotz** [comment]
Just had a chat with Johannes and Daniel for more ideas. Let's do this in a part 2 PR after the dashboard PR:

- [ ] Add tags to annotations
- [ ] Clicking on tags lists them above the tracing list for reference / deselection and filters the list
- [ ] Selecting multiple tags (could) filters them using an "AND" semantic
- [ ] Persist selected tags across sessions in local storage
- [ ] Consider using tracing type (skeleton/volume) and/or dataset name as (automatic) tags
- [ ] Perhaps show last modified date instead of creation date
- [ ] (Consider adding the search terms as temporary tags so that search terms persist)

**Comment by philippotto** [comment]
Sounds very good! AND vs. OR semantics are probably a general problem for search. At the moment it's OR for search boxes, but this should probably be configurable. For search I'd do it the google-way (standard is AND but the user can write "a OR b"). For tags, I'm not sure how to make it configurable (maybe a AND/OR toggle button?).

>  (Consider adding the search terms as temporary tags so that search terms persist)

This is the only thing I'm hesitant to agree with. Filtering Tags should only show tracings which have the desired tag attributes. Search terms on the other hand search through all (or some) properties of tracings. Displaying them as tags would mix two different filter mechanisms.
