### ISSUE TITLE
Backend returns projects without owners

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2007]
When requesting all projects `/api/projects` some projects don't have an owner. This breaks the frontend.

I checked the DB and found no project without an owner. However, when I manually check the project IDs below, they all have reference to an owner, which no longer exists in the DB.

`["5156207de4b06efda8d382d3", "515dcde5e4b06efda8de5c46", "522d06c5e4b0a54e900ccfba", "5523e68378000095ce262bb0", "5527c8a02f0000222fbf0438", "5548b65c6f00005e65fc0732", "555c73a6320000366340d4c9", "5548b6666f00003565fc0733", "55506d016b0000060e461e9a", "5550f4ec6b00002b2447f0aa", "5558a8fd6b0000c54656d82d"]`

@tmbo @jfrohnhofen What's the best course of action here?

1. Delete the projects? (this will likely break some other references)
2. Replace the broken `_owner` references with valid one. Perhaps link these projects to SCM Boy or Heiko's account?
3. Other ideas?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2007/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
do these projects have names or any other meaningful content, that may give us a clue what they are actually about? Then Heiko or someone else from the could have a look? Instead of assigning those to scmboy, I would create a dedicated account that takes ownership of these projects.

Looking at the bigger picture: I would like to get rid of these kinds of problems (inconsistent documents, missing fields, broken references between documents) and suggest the following:
- update mongoDB when moving to new webknossos server
- introduce and enforce schemas for each collection (see #1929)
- since mongoDB does not support foreign-key constraints, have a script that checks all foreign key relationships and reports any errors, so we know about them in time. this script could run on the production DB if fast enough. Otherwise we could run it on the dump as part of the backup

**Comment by hotzenklotz** [comment]
In agreement with Heiko, I assigned the 11 "broken" projects to him. Closing for now.
