### ISSUE TITLE
Searching for a task id that is too short, results in server exception

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#2103]
Posting a request to `/api/tasks/list` with the payload `{ids: ["59cb42"]}` results in `Oops, an error occurred
This exception has been logged with id 75pb5im23.`.

This can be triggered by going to the Tasks view and searching for an id, that is shorter than required. We should probably do some frontend validation there, but nevertheless the server shouldn't return an `Oops` :)

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2103/create?referer=github" target="_blank">Log Time</a>

**Comment by jfrohnhofen** [comment]
@daniel-wer Do you expect the server to still return a result or just a "proper" json error instead of an exception?

**Comment by fm3** [comment]
I would expect an empty result instead of an error. Semantically, no task by that ID exists. The other parts of the query already behave that way, this was only a special case because Mongo is strict about Object IDs.
This is what PR [2019](https://github.com/scalableminds/webknossos/pull/2109) does.
