### ISSUE TITLE
Add pagination to backend API

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2164]
Currently, backend REST requests are limited to 1000 items. We should add pagination to support larger collections.

See. https://discuss.webknossos.org/t/rest-api-for-1000-records/597

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2164/create?referer=github" target="_blank">Log Time</a>

**Comment by rschwanhold** [comment]
@fm3 how consistent should the results be? 
We are currently limiting the SQL-queries with the keyword `limit` and it would be very easy to add an `offset` to the querry, but as this article (https://www.citusdata.com/blog/2016/03/30/five-ways-to-paginate/) points out this comes with a few draw backs:
- it can lead to inconsistency when you already queried the first 1000 tuples, then add or remove a tuple and then query the next 1000 tuple. The result would be that an tuple might be queried twice or not at all. 
- it is not the fastest way

I think the other options (that are pointed out in the article) do not fit very well with our problem because the make use of `Transactions`, only work for ordered queries or a low level PostgreSQL feature.
Therefor I think that `limit-offset` would work best for us if we can live with the draw backs.

**Comment by fm3** [comment]
@rschwanhold thanks for looking into this!
I believe a limit-offset pagination would definitely be an improvement over just the limit of 1000 :)
We should think about use cases where such skipped or duplicate values would be a problem.
I believe the original analyses from the discuss post have been replaced by the project progress and open-tasks screen in https://github.com/scalableminds/webknossos/pull/2233
This issue remained open because hard limits on the API seem problematic.
When we change the rest api to have new optional offset parameters (should not be a breaking change, no new version required), we should of course mention the possibility of inconsistencies in the docs.

The two places where this occurs are 
https://github.com/scalableminds/webknossos/blob/8a24ef2c8721e9ef4b0101eb48d6fb4f55bd92b4/app/models/task/Task.scala#L275 
and 
https://github.com/scalableminds/webknossos/blob/8a24ef2c8721e9ef4b0101eb48d6fb4f55bd92b4/app/models/annotation/Annotation.scala#L123
because those query the truly large collections.


We could of course also discuss if pagination makes sense for other requests like the dataset list. However, if the frontend only loads part of the data there, the frontend-based search/filtering would break, so that should be done with care.
