### ISSUE TITLE
Get rid of MTurk residue

### ISSUE THREAD

**Issue by jfrohnhofen** [scalableminds/webknossos#2230]
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2230/create?referer=github" target="_blank">Log Time</a>

**Comment by fm3** [comment]
@youri-k what’s the status on this?
I would take it from here, assuming that you don’t intend to work on it during the holidays?
Anything I should know?

**Comment by youri-k** [comment]
I don't know if I pushed the latest version of my code but I can do so today. I started deleting the things pretty rigorously and now I get a class not found exception for the mongev plugin which is weird because I thought we removed it completely. Otherwise I didn't remove traits for wK and mturk things but rather deleted the mturk inheritance and removed the match statement. I don't if this is the right approach. 
I think that's everything you need to know...

**Comment by fm3** [comment]
Ok thanks! Yeah, would be great if you could push your latest changes (even if they don’t compile)

**Comment by youri-k** [comment]
Ok changes are pushed.
