### ISSUE TITLE
Disable Error Toast after clicking Logout

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2539]
some request is apparently sent after clicking logout, which produces a toast message
 {"success":false,"message":"Authentication required"}

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2539/create?referer=github" target="_blank">Log Time</a>

**Comment by philippotto** [comment]
@fm3 Is there a specific scenario where this happened to you? From my understanding, this can only happen if a request is **triggered** after the user has logged out. The **arrival of a response** after logout is not problematic, since the cookies are sent when triggering the request.

I guess that's why I couldn't reproduce this issue. It's certainly a problem in theory, but in my opinion not worth fixing, as it's rather unlikely and the ramifications are also not really disastrous.

**Comment by fm3** [comment]
closed as too-low priority

**Comment by fm3** [comment]
seems I’m not the only one noticing that https://discuss.webknossos.org/t/logout-errors/1158

**Comment by hotzenklotz** [comment]
I am unable to reproduce this bug. I am not sure if this has been solved in the meantime. Is there a way to reliable re-produce this issue?

@fm3 Do you still have this happening?

**Comment by fm3** [comment]
Couldn’t reproduce it anymore either, maybe it has been fixed as a side-effect of something else. I’ll reopen if it happens to me again
