### ISSUE TITLE
speed up CI

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#2552]
ideas:
* [x] slim down sbt docker image
* [ ] don't build same things twice (merges into master)
* [x] use newer scala

**Comment by philippotto** [comment]
For the record, parallelization didn't yield easy wins (a single container was already at its limits and sharing data between multiple container added overhead which was higher than the actual benefit). Instead, I optimized different things to get the compile time down (see #3231).

One optimization is to not run some tests on master builds as they were aleady executed for the dev branch. Skipping the entire build is probably not as easy, since things like the build info differ between master and dev branch. For that reason, I would scratch the " don't build same things twice (merges into master)" checkbox from above.

Using newer scala (and/or sbt) is probably still a good idea. However, this should probably be done by somebody else :)

**Comment by jstriebel** [comment]
@philippotto I agree that `" don't build same things twice (merges into master)"` adds too much complexity. As scala is upgraded, can we close this then?

**Comment by philippotto** [comment]
Sure!
