### ISSUE TITLE
Check Team and Project Name Validity in Frontend

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2591]
for example team names and emails have regex checks in the db schema. it would be useful to ensure this is all also checked in the frontend

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2591/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Which schema properties are you referring to? The frontend already validates emails, the length of certain fields etc.

**Comment by fm3** [comment]
right, I did not go through the list, turns out to be very small. I noticed this for team names ( https://github.com/scalableminds/webknossos/blob/master/tools/postgres/schema.sql#L194 )

**Comment by philippotto** [comment]
https://github.com/scalableminds/webknossos/blob/master/tools/postgres/schema.sql#L174

**Comment by philippotto** [comment]
The same issue exists for project names (e.g., must not contain spaces). I changed the scope of the issue. So please tackle that, too, @MichaelBuessemeyer  :)

**Comment by MichaelBuessemeyer** [comment]
@philippotto Actually this is already handled in the project-create-view (https://github.com/scalableminds/webknossos/blob/ea0856fc3c9cc5b0dfb161924f763ace7943de64/app/assets/javascripts/admin/project/project_create_view.js#L103).
I could not find any other possibility to change the name a project.

**Comment by philippotto** [comment]
The referenced code only checks for a minimum length. But it does not ensure that the name doesn't contain spaces, which seems to be a constraint (at least, I cannot create a project when the name contains spaces). However, I'm a bit confused since the mh lab wk instance has projects with spaces in it.

@fm3 Does the backend forbid spaces in names? The regex doesn't look like that, but I'm not sure whether there's some other magic which ensures this constraint: `  name VARCHAR(256) NOT NULL CHECK (name ~* '^.{3,}$'),`

**Comment by fm3** [comment]
@philippotto @MichaelBuessemeyer Correct, the database has a weaker check, to still allow the legacy names. However, when creating new projects, the name must also pass the stricter check in https://github.com/scalableminds/webknossos/blob/master/app/models/project/Project.scala#L69
