### ISSUE TITLE
Project Progress Screen: make »Unauthorized« toast sticky

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2656]
this screen just “freezes” if the cookie becomes invalid

**Comment by philippotto** [comment]
@fm3 If the cookie becomes invalid, this message is shown:

![image](https://user-images.githubusercontent.com/2486553/41777444-9e2753ba-762b-11e8-8be6-16415c90df88.png)

However, the toast will disappear after some time, leaving a "loading" state. Do you want that the toast sticks around (until dismissal maybe). Or are we talking about different things?

**Comment by fm3** [comment]
That’s already good, I hadn’t tested this myself. 
The screen was reported to be just frozen. Maybe it would be helpful to make the toast sticky, as you said. Does it also come if the request is not the first, but one of the periodically triggered ones?

**Comment by philippotto** [comment]
> The screen was reported to be just frozen, but maybe they just missed the popup.

The screen could be frozen when the "refresh" button was clicked explicitly and that request failed. However, I merged some changes which fixed this. On a periodic refresh, this should not happen. Instead, toasts should be shown if there is a server error.

The ideal solution would be to make the "toast timer" start ticking on user interaction (e.g., mouse move). However, this is a bit more complex, since antd does not support this.

I'll close this for now, since I think the current state is fine. We can re-think this when issues re-appear.
