### ISSUE TITLE
repair unnamed trees of tasks in fossilDB

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2721]
see #2686

**Comment by fm3** [comment]
@daniel-wer can you estimate when the issue started to happen? then we don’t have to go through the entire database

**Comment by daniel-wer** [comment]
@fm3 I'll try my luck with the git history and will report back :)

**Comment by daniel-wer** [comment]
Just referencing the last time this bug was present (May, 2017):
https://discuss.webknossos.org/t/tree-names-in-compound-tasks/254/10
https://github.com/scalableminds/webknossos/issues/1616

All old trees that had no name at this point, supposedly have been renamed according to the issue and discuss post.
I'll try to find out when this broke again later.
