### ISSUE TITLE
Add possibility to randomize Task search result sample

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2803]
When searching for all Tasks of a project, only max. 1000 results are returned. There should be the possibility to randomize this 1000 result sample, so that tasks from across the project are returned.

related to but not exactly a duplicate of #1297 – but if this one is solved, I guess the old one loses all priority.

**Comment by daniel-wer** [comment]
Heiko commented this

> X randomisierte wäre gut (1000 ist bisschen viel), danke !!

but I think as the results are paginated anyways, simply returning the default maximum number of 1000 tasks should be alright :)

**Comment by rschwanhold** [comment]
@daniel-wer does this issue refer to `task_list_view` or `dashbord_task_list_view`?

**Comment by daniel-wer** [comment]
@rschwanhold This issue refers to the `task_list_view` where an admin can search for tasks using id/taskType/project/user. The result in this view is capped to the first 1000 tasks, so they would like the possibility to see 1000 random tasks instead of the first 1000.
The `dashboard_task_list_view` shows the tasks a specific user needs to work on, which most of the time are less than 5.
