### ISSUE TITLE
Allow to "activate" a tree group

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2871]
As a result, actions such as renaming and toggling visibility should be applicable to groups, as well. Tree manipulating actions should be blocked (such as create node).

Also see: https://discuss.webknossos.org/t/promoting-groups-to-first-class-citizens/991/3

I suspect this to be quite a bit of work, since our code assumes that there is always an active tree. @daniel-wer What do you think?

**Comment by daniel-wer** [comment]
Hmm, at least according to our flow type definitions, the `activeTreeId` of a tracing can be null/undefined, so type-wise we may have sufficient checking in place (using maybes). However, there could (and probably will) still be some logic errors.

I predict discuss issues like "I can't create nodes", because a group is active, but maybe people will get used to this quickly (and not many people are using groups at the moment I think).
