### ISSUE TITLE
Team manager cannot activate new users

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3043]
[Link to Discuss](https://discuss.webknossos.org/t/bug-in-user-activation/1056)

Probably a back-end issue?

**Comment by fm3** [comment]
Note that this is [by design as requested](https://discuss.webknossos.org/t/organizations-and-team-management/789/2), but I can change it now, of course.
Generally speaking, I get the feeling that the Team Manager model doesn’t work well anymore (they were originally intended to be allowed only team-specific things, but we are gradually giving them more rights) – maybe we should do a general discussion about this.
