### ISSUE TITLE
`value`  used in correlation with `getFieldDecorator` creates a warning by antd

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#3071]
```Warning: `getFieldDecorator` will override `value`, so please don't set `value` directly and use `setFieldsValue` to set it.```
This error occurs in the create-task-view (but maybe also some others where a form with FieldDecorators is used).

The correct way how to set the value not via the `value` attribute is described [here](https://ant.design/components/form/?locale=en-US#Form.createFormField).

**Comment by daniel-wer** [comment]
I had a quick look and this is about the `Vector3Input` and `Vector6Input`. The problem is that these are sometimes used as part of a form (in combination with getFieldDecorator) and sometimes as standalone inputs. When used as part of a form, the value prop should not be set as the fieldDecorator will take care of that - when used on their own, the value should be set. Not sure what the most elegant solution for this is. /cc @philippotto

**Comment by MichaelBuessemeyer** [comment]
The behavior of the affected components is correct thus the warning can be ignored, beacuse there is no easy workaround for this.
