### ISSUE TITLE
Show »Activate User« button to team managers

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3091]
they are allowed to do it now and the blue »there-are-new-users« notification shows it, so the normal user list should show it now too (not disable, though)

**Comment by MichaelBuessemeyer** [comment]
@fm3 The actual problem is that we use the api call `http://localhost:9000/api/users?isEditable=true` and this does not return the "newly added users".
The two solutions I came up with are: 1. user `http://localhost:9000/api/users` instead and display only the users that are editable (-> filter in the frontend) and get all also getting all new and not activated users to display the activation notification.
2. Someone adds the new users to the editiable users. Which isn't optimal in my opinion, because a call to `http://localhost:9000/api/users?isEditable=true` would then also include non-editable users, although the parameter in the call clearly says that only editable users are sent.

**Comment by daniel-wer** [comment]
@MichaelBuessemeyer I don't think that is the problem - as it works for admins. Beware, that by default the inactive users are not shown, you have to remove the `Show Active Users Only` badge at the top of the user list first. Then the inactive users are shown in the user list, even for team managers. Can you confirm that?
In the code of the `user_list_view`, line 450 and following, there is a check 
```javascript
                 {// eslint-disable-next-line no-nested-ternary
                  this.props.activeUser.isAdmin ? (
                    user.isActive ? (
                      <a href="#" onClick={() => this.deactivateUser(user)}>
                        <Icon type="user-delete" />Deactivate User
                      </a>
                    ) : (
                      <a href="#" onClick={() => this.activateUser(user)}>
                        <Icon type="user-add" />Activate User
                      </a>
                    )
                  ) : null}
```
which would need to be rewritten for this to work as expected :)

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer So this issue addesses the possibility to activate/deactivate a user in the users list and not to "confirm a registration" of a user that is done by clicking on the "Activate User"-button in the Alert with the title "There are new inactive users" that appears between the list and the buttons at the top? If that's so, I got a misunderstanding here :smiley:

**Comment by daniel-wer** [comment]
It refers to both cases, but one doesn't work yet. The current state is, that for a team manager!, the recently registered users are shown above the user list and can be activated! BUT when showing inactive users in the user list, the link to activate those inactive users is not shown in the user table. It should, however, be displayed, that is what this issue is about.
"Confirm a registration" and "activate a user" are the same thing :)

**Comment by MichaelBuessemeyer** [comment]
Ok now I get it. 
But it is still a necessary that the users that gets activated is part of the team the logged-in user manages, right?

**Comment by fm3** [comment]
Users only get team memberships when they are activated. Hence, any team manager can activate all new users of the organization –but then only assign them to teams they manage

**Comment by MichaelBuessemeyer** [comment]
So my concern above was correct, because `http://localhost:9000/api/users?isEditable=true` does not return the newly registered users (atleast for me using the master branch). But if I (as a admin) activate this user and assign him to the team user A is in charge of and then deactivate him. Only then the new user appears to the manager A as a new user.
=> I need the `http://localhost:9000/api/users` call to get all users and from the i need to filter for all new users, do I deeply misunderstand something here :thinking: ?

**Comment by fm3** [comment]
I’m not really immersed in the subject, i’ll have a look tomorrow. :)

**Comment by MichaelBuessemeyer** [comment]
If we change the isEditable route we need to consider that this might affect other parts in the frontend.

This route is used by: task_search_form => should not be affected, because the result gets filtered for only active users.
Same goes for time_line_view => Should not affect these components. :smiley:

**Comment by fm3** [comment]
see my description in PR #3100
