### ISSUE TITLE
Use URLs for dashboard tabs

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3134]
We could use URLs for the tabs of the dashboard, e.g. `/dashboard/{gallery,datasets,tasks,annotations}`.

**Comment by philippotto** [comment]
I reverted the corresponding PR, since the admin functionality "view tracings/tasks of user" broke (when switching tabs, at least). @MichaelBuessemeyer You can revert my "reverting PR" (there is a revert-button on this page: https://github.com/scalableminds/webknossos/pull/3216) and fix the bug on that branch then.
