### ISSUE TITLE
benchmark fossildb performance

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3290]

**Comment by rschwanhold** [comment]
I did some investigation about the performance of fossildb. 
More specifically, I have tested the following methods of fossilDB: `get`, `put` and `getMultipleKeys`.
I generated two different types of test data: One big NML-file (50mB) and 2300 small NML-files (each 21,4 kB, together 50mB)
Results:
-   put:
(I ran every request 10 times to get more accurate results)
Variant 1 (big nml-file): The sum of the 10 `put`-requests for this file took 5-6sec
Variant 2  (many small files): The sum of the 10 * 2300 requests took 9sec. (The requests of one 2300-batch were run in multiple threads. My computer has 2 real cores with hyper-threading)
-   getMultipleKeys:
I have filled the fossilDB with the random NML-files by running 10 * 2300 `put`-requests (each with a different key) to get a lot of keys.
I requested all keys three times in a row, then cleared the fossilDB and started the process again. I got a timeout every time, when I requested all keys.
first request: timeout after 2:30 min
second request: timeout after 1:17 min
third request: timeout after 1:15 min
When I sent an request, under the same conditions as before, which limits the requested keys to 2300 it took about 30sec

Because of this data, I think that fossilDB is better in handling big files (about 50mB) than many small files. Many small files would also increase the amount of keys which would slow down the `getMultipleKeys`-requests.
