### ISSUE TITLE
Add support for removing datasets

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#3396]
In Webknossos, it seems that I can't remove a dataset. When I delete it from the hard drive, it will still show up in the datasets list:
![screen shot 2018-10-24 at 13 08 53](https://user-images.githubusercontent.com/1701960/47426617-fd031b80-d78d-11e8-896e-7205a0241b5b.png)
This clutters the datasets list with datasets that no longer exist.

On Version 18.10.0.

**Comment by philippotto** [comment]
Sounds good! Deleting should probably be only possible for datasets which are not imported anyway.

**Comment by fm3** [comment]
We have decided that deleting datasets is dangerous, since we use their names to identify them. This would create ambiguity when a dataset of the same name is created later. 
Also, annotations that were created for that dataset will no longer be accessible.
The “recently used” sorting algorithm should push the outdated datasets down in the list, keeping the clutter acceptable
