### ISSUE TITLE
Fill feature in volume tracing

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3488]
Consider the brush mode in volume tracing. A typical workflow is to brush the outline of a cell first and fill it up later. The filling could be automatic when the outline is closed. Ideally the user would brush a cell's outline and press a keyboard shortcut to fill the just brushed cell.
When the outline is not closed or leaves the viewport, nothing should be done on filling.

**Comment by philippotto** [comment]
The difference to the outline tool is that the mouse can be released in the meantime? We could also have a "polygon"-tool which would allow to release the mouse while annotating a cell.

The photoshop tool I'm thinking of (not sure whether its polygon) allows the following:

- create multiple points (by clicking) which are connected with straight lines
- drawing segments of the polygon by keeping the mouse button pressed

Essentially, this allows to draw an outline similar to our existing outline tool while being able to lift the mouse button. Pressing del could also undo the last segment (that's how it's done in PS).

Might be more intuitive overall since?

**Comment by normanrz** [comment]
I think brushing is much faster than tracing because you can instantly correct any inaccuracies by just wiggling the mouse. With trace you need to complete the full outline first and then correct.

I don't think polygon has much value. TrakEM has it (https://youtu.be/DU0S2fX5EFU?t=85) but I don't see why it could be any better than brushing.

**Comment by normanrz** [comment]
Auto-fill in VAST is pretty nice: https://youtu.be/E0k9GuxVePs?t=466
