### ISSUE TITLE
have any recent datastore changes impacted data loading speed?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3499]
related: https://discuss.webknossos.org/t/admin-notification-in-case-of-degraded-performance/1220/3

**Comment by rschwanhold** [comment]
@fm3
I've added a route that triggers 1000 requests to the datastore (to get random data of a dataset).
The code is here: https://github.com/scalableminds/webknossos/tree/add-speedtest-for-datastore
The  first commit only added a speedtest for the current master and the second commit reverted significant changes over the last half year that could have led to performance impact (https://github.com/scalableminds/webknossos/commits/1cfaf4f87b84491398059c9d980834f7949443cf/webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/Cube.scala). 

The current master seems to be a bit slower on average, but not significant. (see results below).

How I measured the times:
I started webknossos and viewed the dataset in the browser for a short period of time to make sure that the startup process of webknossos is finished and does not influence the measurements.
I triggered the route for the speedtest with postman to find out how long this takes.
I triggered the route an additional 6 times until the measurements seem to do not change anymore.

Then checked out the current master and repeated the steps from above. (and restarted Postman)

***Results:
current master: 1452ms, 1007ms, 826ms, 750ms, 623ms, 572ms, 556ms
old master: 1386ms, 952ms, 672ms, 690ms, 464ms, 606ms, 537ms***
 ("old master" refers to the commit where significant changes were reverted)

I assume that the values decreased because of caching.

Notes:
I am using the postman desktop app and I don't know how it handles caching and if that could have an impact on the results

**Comment by fm3** [comment]
Thank you very much! This is enough data to rule out that the decreased performance was caused by those datastore changes :) That’s good news for us because those changes were rather necessary to avoid race conditions.
I would now assume that the perceived decreased performance was due to the front-end’s bucket loading strategies not being optimized for very strongly anisotropic data.
