### ISSUE TITLE
WKW Dataset support for Neuroglancer

### ISSUE THREAD

**Issue by unidesigner** [scalableminds/webknossos#3526]
Hi! I was wondering whether there is a plan to implement support in Neuroglancer for the WKW datasets (and/or KNOSSOS Cube datasets)? It would be great to be able to browse the datasets on demo.webknossos.org as well in Neuroglancer. This would be the reverse from #3517.

**Comment by philippotto** [comment]
Hi Stephan,

at the moment, there is no active plan to implement such support. Can you elaborate why you are interested in this? Which features of Neuroglancer are you personally interested to use with WKW datasets?

We are actively trying to extend webKnossos' feature set and maximize usability for viewing and annotating datasets. Your input would be very interesting for us in order to prioritize.

Thanks!

**Comment by unidesigner** [comment]
Hi Philipp,

I'm building a platform for comparative connectomics - braincircuits.io - and I like to link published raw datasets with their publication. I link to a number of WebKnossos datasets already available on demo.webknossos.org. There is a link that directly opens the webpage and dataset. In general I'd prefer to be able to browse dataset with one viewer application making it easy for new users (each tool has different keyshortcuts, mouse navigation etc.). I think Neuroglancer did a great job to support the many backend volume datastore types available and is great for browsing. IMHO there is a too big proliferation of chunked volume data storage formats (CATMAID tile sources, KNOSSOS formats, n5, Neuroglancer formats, HDF5, zarr, BOSS, DVID etc.) which also limits interoperability of clients and annotation tools.

In the long-term, I do not think it makes sense to have competition at the level of the image file formats or use it to encapsulate different developer communities. It would be nicer to have some competition and differentiation of features/tools e.g. at the level of the annotation tools itself (such as webKnossos, CATMAID, neuroglancer etc.) that can load and render different image data sources.

Having the demo.webknossos.org page as a repo with different datasets is great, but I think the community would benefit a lot by being able to access and browse these dataset with as many client tools as possible. And as far as I can tell, it should not be too complicated to add WKW dataset support.

Greetings, Stephan

**Comment by philippotto** [comment]
Hi Stephan,

thanks for your valuable input. Also, kudos to braincircuits.io!

Our [WKW](https://github.com/scalableminds/webknossos-wrap) format is open source and has bindings for different languages (Python, C, Matlab). So, if somebody wants to pick up this task, they should be able to integrate wkw into Neuroglancer easily. At the moment, however, this issue is not a priority for us.

Nevertheless, I'll leave this issue open for our backlog, since I agree with the general rationale you described. Thanks again for your input!

**Comment by unidesigner** [comment]
Ok, no worries.

I will give the Python-wrapper for the WKW format a try. Is it possible to open remote data sources (like from demo.webknossos.org) with it, e.g. to download a subvolume of the raw and/or segmentation data?

**Comment by normanrz** [comment]
Currently, the python library can only access WKW files via file system (either local or network storage). We are thinking about an API to download subvolumes of data while making sure that webKnossos stays performant for tracing.
