### ISSUE TITLE
Batch google analytics requests

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3537]
Performance-wise the sheer amount of HTTP requests GA causes is far from ideal.

**Comment by daniel-wer** [comment]
While working on this I discovered that google analytics has pretty strong rate limiting of 500 hits/session.  We've been missing a lot of events in our analytics data because of that. We therefore decided to get rid of the redux actions tracking which more or less makes the need to batch requests obsolete as we won't send as many requests in the future. For reference a gist with the analytics.js code with batching support that I originally wrote for this issue: https://gist.github.com/daniel-wer/3c242c4ddc72db55989cad5653e34184

The redux actions tracking will be replaced by targeted hit tracking for specific user actions, see #3459
