### ISSUE TITLE
Available mappings list should be up to date

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3648]
refresh, reload or mappings.getAll should trigger looking on disk?

**Comment by philippotto** [comment]
> (1) the “reload” button could (next to clearing data cache) trigger re-exploration and automatically save the new json if no errors occur

I vote for that :+1: As far as I know, users usually hit `reload` for the dataset they are iterating on, anyway. (Btw, they also often use `refresh all datasets` since they don't know what the actual impact is).

> (2) this could even happen for all datasets when hitting refresh/reporting datasources (probably slow though, doesn’t seem right to me)

I wouldn't do that, since (a) slow and (b) the users already do the "reload" thing.

> (3) mapping-specific: the front-end call mappings.getAll could issue a request to the datastore server to list mappings on disk, rather than print the already reported ones.

Hmm, could work, too, but I would make it rather another explicit button (refresh mappings), so that it doesn't happen on every page load. This is also good for fast iteration, since the page does not a refresh (potentially).

So, maybe the get mappings route could have an additional parameter `forceRefresh`?

**Comment by jstriebel** [comment]
To me it would be most natural if the `datasource-properties.json` would be updated when the mappings are written, and this would be reported as usual (refresh button & every 10 min). Are the mappings generated from webknossos or via scripts or both?

**Comment by georgwiese** [comment]
In our case via a script. We also update the `datasource-properties.json`, so it works for us as is. But still, it's kinda redundant and can lead to the situation where you can activate a mapping that's not listed when calling `mappings.getAll()`.
