### ISSUE TITLE
Isosurface for volume annotations

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3681]

**Comment by philippotto** [comment]
I discussed with @fm3 that we would like to support the basic use case of having isosurfaces for a volume annotation (without fallback layer) . These isosurfaces could be calculated on the tracing store with low implementation effort™ (since the data store is already capable of doing so).

Incrementally changing a volume annotation wouldn't have the best speed (since the changes have to be sent to the server to re-compute the isosurface there), but we think that this is okay for now.

Later, we can always think about computing the isosurfaces locally (marching cubes in webworkers?) to achieve isosurfaces for volume tracing *with* fallback layers and faster feedback loops for editing annotations.

Consequently, the following needs to be done:
- [ ] backend: implement compute isosurface route for volume tracings (analogous to isosurfaces for segmentation layers)
- [ ] frontend: allow isosurface computation for volume/hybrid tracings *without* fallback layer
