### ISSUE TITLE
Iteration on publication gallery

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3740]
Now that we have the first version of the publication gallery (which already is great!), we can do some iterations on it. What comes to my mind:

- [x] Add dataset size (in nm, µm or mm)
- [ ] Add Publication date
- [ ] Add Organization name
- [x] Full width list layout instead of 2-columns
- [x] Rename heading to "Featured publications"
- [x] How can I get to the frontpage when I'm logged in?
- [x] Hide Publication gallery when empty #3733 
- [x] Sort datasets in publication by sorting key

**Comment by daniel-wer** [comment]
> Hide Publication gallery when empty #3733

I'm having trouble with this. In order to hide the publications tab, we need to check whether any of the datasets have a publication. So we need to wait until the datasets are fetched until this can be decided. Some of the dashboard tabs show cached data while the datasets are loading, though, so we want to display those tabs BEFORE the datasets are fetched. This would lead to tabs appearing/disappearing.

I would propose to enable the publications tab using a feature flag, what do you think?
And if so what should be displayed when logged out and there are no publications?

>  How can I get to the frontpage when I'm logged in?

What do you mean with this? What is the frontpage? The user is redirected to the dashboard if the wK logo or "Dashboard" is clicked.

**Comment by normanrz** [comment]
I think these are 2 faces of the same issue. As frontpage I mean the page with the publication gallery and the informational header. In the future the frontpage could also contain links to features, pricing etc.

Example: When I go to https://circleci.com/, I see the frontpage regardless of whether I'm logged in or not. https://circleci.com/dashboard brings me to the logged-in area.
In webKnossos I cannot reach the frontpage again, when I'm logged in. Maybe we strip the publication from the logged-in area (i.e. dashboard) and add a mechanism to view it again. I think that would be great for the demo instance. Maybe not so useful for the other instances. What do you think?

**Comment by daniel-wer** [comment]
Thanks for clarifying :) I like the idea of stripping the publications page from the dashboard as it is no longer relevant in that context.
Regarding the circleci example, I can't find a quick way to go to the circleci frontpage from the dashboard of a project, either, except of course entering the URL directly (should we make `/` also go to the frontpage rather than the dashboard?). If I understood you correctly, you want an additional link/button to get back to the frontpage for the demo instance? We could also make it so that clicking on the wK logo goes to the frontpage :)

**Comment by normanrz** [comment]
Good point. I'm not sure a dedicated button is required. The topleft logo could work, if that doesn't confuse existing users.

Would it make sense to single-out the demo instance for that? For the lab instances, `/` should maybe be directly the login screen or dashboard.

**Comment by daniel-wer** [comment]
Yes that probably makes sense. I'm a little afraid that demo will deviate from the usual (and tested) UI more and more, but that's not yet not a problem I'd say. If we find a well named config/feature flag that switches these things, we should be alright.
