### ISSUE TITLE
enable archiving of datasets

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3773]
the name will still be blocked for new datasets. @philippotto mentioned it may be difficult for the front-end to list archived ones (in order to then undo this)…?

**Comment by philippotto** [comment]
> [...] it may be difficult [...]

Yeah, the current handling of unarchived/archived for exploratives and tasks is a bit tedious at the moment (since back-end pagination is also included etc). Maybe this is a chance to refactor that with react hooks to extract some of the logic more nicely?

However, a first'n'fast solution could also be to just hide archived ones and make the UI very dramatic by:

- naming the action "delete"
- adding a "are you really, really sure you want to delete this dataset?" confirm

We could also only allow this for datasets which don't exist on disk anymore.

**Comment by fm3** [comment]
Would this be made easier if the backend supplied two separate routes for the archived and active items respectively? (Rather than have it both in one paginated list).

I think “delete” might lead to confusion about why the name is still reserved, so I’d be hesitant to go for this quick solution.

**Comment by philippotto** [comment]
> Would this be made easier if the backend supplied two separate routes for the archived and active items respectively? (Rather than have it both in one paginated list).

Hm, no, I think, it should be consistent with the other archivable routes, so that we can abstract it elegantly.

> I think “delete” might lead to confusion about why the name is still reserved, so I’d be hesitant to go for this quick solution.

Ok, I understand. However, I think there is a more general problem. A typical workflow would be: delete dataset from disk, hit "archive" in wk, move new dataset folder onto disk. Now, if the user chose the same names, the "new dataset" will not show up because wk thinks its still the old one and that is archived.

I'm not sure how we could avoid this problem :thinking:

**Comment by fm3** [comment]
> Hm, no, I think, it should be consistent with the other archivable routes, so that we can abstract it elegantly.

Well if it would actually help we could do that for all of them. :) But I can’t judge that.


>  Now, if the user chose the same names, the "new dataset" will not show up

True, this is not the workflow we want. And a warning on the archive button would only help short-term. Let’s maybe brainstorm about that in person in the coming days

**Comment by philippotto** [comment]
> > Hm, no, I think, it should be consistent with the other archivable routes, so that we can abstract it elegantly.
>
> Well if it would actually help we could do that for all of them. :) But I can’t judge that.

Perf-wise the current approach makes more sense, which is why I'd stick to that :)

> > Now, if the user chose the same names, the "new dataset" will not show up
>
> True, this is not the workflow we want. And a warning on the archive button would only help short-term. Let’s maybe brainstorm about that in person in the coming days

Yes, that's definitely important to discuss!

**Comment by philippotto** [comment]
1. backend delivers datasets with a boolean "archived" flag which is true iff the dataset folder is missing on the disk. the front-end filters according to that.
2. later, we can have two different routes to speed up loading. the front-end should be refactored (maybe via hooks) to elegantly handle the archived/unarchived entities for datasets, tasks and tracings.

**Comment by philippotto** [comment]
Closing this in favor of #3961 which captures the remaining "todo" a bit better.
