### ISSUE TITLE
Support for uint16 color data

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3781]
Many microscopes, CTs etc output 16 or even 32 Bit data. WKW also supports these formats. Would be great if wk could also display this data. I think the data would be recalculated to 8-Bit in a shader with contrast/brightness settings in mind.

**Comment by philippotto** [comment]
Let's investigate the amount of work needed for this by looking at our code thoroughly.

**Comment by philippotto** [comment]
From my investigation, the required effort should be minimal. `getData` isn't called on many sites and the interface of `getDataValue` (which uses `getData`) should stay untouched. Most of the code, which is interested in the actual bucket data, is segmentation code anyway (for which we already support uint16).

Two things need to be done:
- [ ] adapt the shader so that 16 bit color data is correctly displayed
- [ ] ideally, refactor the data bucket class to not use Uint8Array everywhere but instead use a data view which depends the actual format. not too sure, though, whether it's worth it. can be investigated when doing actually doing the issue.

**Comment by daniel-wer** [comment]
I just did another small test with a uint16 layer I built to see what's still needed for this (now that we've added the float layer support and generalized the data handling a bit):

- [ ] adapt the shader so that 16 bit color data is correctly displayed (ideally should be done in conjunction with the histogram PR to avoid merge conflicts)
- [ ] the backend doesn't send enough data for uint16 color layer buckets, looks like it automatically assumes uint8 (/cc @fm3)
