### ISSUE TITLE
Strip any PR or issue reference from slack notification

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3903]
Strip any `#\d+` from the commit message in circleci-slack-notification, less confusion

**Comment by fm3** [comment]
I actually find it very useful to have a link to the PR in the slack notification. I have often clicked it to quickly double check that a PR does not have datastore/tracingstore changes. 
I think since the build numbers are always five-digit now, while issue numbers will stay four-digit for a while, there hasn’t been an occurence of the PR number being mistaken for the build number. Do you agree?
