### ISSUE TITLE
Find data route does not support uint24 layers

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#3936]
For local testing i use the `fluro-rgb_knossos` dataset.
Using the frontend button for the find data functionality results in a bug. ![Screenshot from 2019-03-21 16-37-32](https://user-images.githubusercontent.com/39529669/54764774-aee92b80-4bf8-11e9-9ced-63097c8e0239.png)

Full error info: 
```Execution exception
[MatchError: uint24 (of class scala.Enumeration$Val)]
In /home/michael/Desktop/ScalableMinds/webknossos/webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/FindDataService.scala:29
26  private def checkAllPositionsForData(dataSource: DataSource, dataLayer: DataLayer) = {
27
28    def convertData(data: Array[Byte]) =
29      dataLayer.elementClass match {
30        case ElementClass.uint8 =>
31          convertDataImpl[Byte, ByteBuffer](data, DataTypeFunctors[Byte, ByteBuffer](identity, _.get(_), _.toByte))
32        case ElementClass.uint16 =>
33          convertDataImpl[Short, ShortBuffer](
```

**Comment by fm3** [comment]
Interesting find. This is a bit tough, since our find data mechanism relies on buffers with data types of the appropriate size, and we don’t have one for 24 bit.
This could be reengineered to check the bytes directly, rather than converting the data. @youri-k what do you think? I’d say, though, this is not super high-priority. @MichaelBuessemeyer does this block your work, is there a special reason you are using this dataset for your tests?

We should probably also check other parts of the datastore code for places that falsely assume that there is 2^n-bit-ness per element

**Comment by MichaelBuessemeyer** [comment]
@fm3 No this doesn't block me in any way. I just accidentally found it out while testing something else 🙂.

**Comment by philippotto** [comment]
We should at least hide the button for rgb datasets, if we don't want to implement the actual support right now.

**Comment by fm3** [comment]
We decided that this should be tackled in this sprint. The idea is to look at the bytes directly, rather than convert them. If all (1, 3, 4 or 8) bytes are zero, there is no data at that position
