### ISSUE TITLE
Support for high/low res datasets

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4026]
A dataset that has high res (e.g. 12x12x30nm) in a small ROI and low res in the rest of the space (e.g. 64x64x30nm)

**Comment by philippotto** [comment]
For this, we would need to figure out how to unify the addressing for the different scales. Right now, addressing data positions is done via voxel coordinates (see user-exposed position UI). In case, of differing scales, this would not work, anymore. Due to backwards compatibility (also for NMLs), I assume that we would need to come up with some (unelegant) workaround for this problem.

**Comment by normanrz** [comment]
A quick sketch of how the high and low res pieces would be composed together:
![IMG_1262](https://user-images.githubusercontent.com/335438/56812250-cab8a080-683a-11e9-989f-a91ad12700bc.jpeg)

We could keep the constraint that the voxel sizes need to be compatible (multiple of 1,2,4,8,16,...).

**Comment by fm3** [comment]
@philippotto do you think https://github.com/scalableminds/webknossos/pull/6748 (possibly together with the upcoming https://github.com/scalableminds/webknossos/pull/7395 ) solve this? I guess more specific follow-up issues can be written later for additional requried features?

**Comment by philippotto** [comment]
Yes, the basic support for the feature described in this issue is already implemented. I don't see value in keeping this issue open. Thanks for pointing this out :+1:
