### ISSUE TITLE
Cheap support for uint64 segmentations

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4163]
For large segmentation projects, uint64 is required to have enough segment ids. Implementing 64-Bit support in the frontend is very complicated due to the lack of native 64 bit datatypes in JS and WebGL.

Therefore, I'm proposing to handle that on the datastore side. The datastore would sliently or explicitly (tbd) cast uint64 to uint64 by removing the higher bits. The resulting collisions may be acceptable for viewing the data since they are likely to be distributed over the dataset.

Any thoughts @fm3 @daniel-wer ?

**Comment by philippotto** [comment]
> cast uint64 to uint64

You probably meant uint64 to uint32, right?

By itself, the suggestion sounds okay and easy to implement, but I'm a bit anxious about the collisions which will result in very rare and very weird "bugs". We should definitely show a user warning when doing such clippings. Also, it might be useful to be able to explicitly retrieve the "unclipped id" for a certain location, so that the user can manually check whether she sees a merge error or not.

**Comment by normanrz** [comment]
> > cast uint64 to uint64
>
> You probably meant uint64 to uint32, right?

Correct!
The question is whether the clipping should be done in the back- or frontend. If it is done in the frontend, access to the unclipped values would be easy?

**Comment by philippotto** [comment]
> The question is whether the clipping should be done in the back- or frontend. If it is done in the frontend, access to the unclipped values would be easy?

True, however, I'd think that the performance overhead of doing this in the front-end might not be worth it (memory, bandwidth etc.). If the "true data access" is quite rare (e.g., by manual invocation of the user for one voxel), we could still ask the back-end for the unclipped data ad hoc.

**Comment by philippotto** [comment]
- [ ] mapping support
