### ISSUE TITLE
Adapting brightness / contrast before histogram is loaded breaks page

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4210]
`this.props.data is undefined` was the error message. Maybe connected to RGB layer? @valentin-pinkau might be able to provide more info.

**Comment by MichaelBuessemeyer** [comment]
I think this issue is outdated. It was created more than half ago. A lot of changes have been made to the histogram during this time.
And the issue seems to have occurred in the file `histogram_view.js`. But in the dataset settings, there is always passed data to all rendered histograms. If no data is available, dummy data will be passed to the component. see [here](https://github.com/scalableminds/webknossos/blob/6aeaaaf742b9f6d58241456bd0c37bbe5315b2f7/frontend/javascripts/oxalis/view/settings/dataset_settings_view.js#L167).
Thus it should never be possible for `this.props.data` to be undefined.

I suggest to close his issue and reopen it when this bug occurs again.

**Comment by philippotto** [comment]
> I suggest to close his issue and reopen it when this bug occurs again.

:+1:
