### ISSUE TITLE
Simplify/fix basic docker setup for single instances

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4221]
If I simply run wk with docker on a server with ip X, I'd like to be able to visit `http://X:9000` and everything should just work. Instead, the communication with the datastore fails since it wants to communicate with `localhost`.

At the moment, I change the datastores manually within the database that gets reset by wk sometimes.

It would be cool if we could make this scenario more hassle-free.

**Comment by normanrz** [comment]
To implement this, I believe, we need an additional `publicUrl` for data and tracing stores. webknossos and the stores would continue to use the `url` and the frontend would use the `publicUrl`. The rest can be done with some docker-compose magic. 
The data and tracing stores probably don't need to know the `publicUrl` of webKnossos since they are not creating user-facing links?

pinging @fm3 @youri-k

**Comment by fm3** [comment]
sounds about right to me

**Comment by youri-k** [comment]
@normanrz @fm3 the backend part should be finished and ready for review

**Comment by fm3** [comment]
@youri-k that’s #4286, right? could you fill in the template so that we know what to look for?

**Comment by normanrz** [comment]
I think your PR can be merged w/o the work that I still need to do.
