### ISSUE TITLE
In case of fossildb overload, saving fails with misleading error message

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4263]
users wrongly see the “edited in multiple windows” error message – can we distinguish this better?

**Comment by youri-k** [comment]
I think this is rather hard to distinguish because the [TracingStore](https://github.com/scalableminds/webknossos/blob/7708a79bd8dc2ba49d10c0fa3a7fd522437b0aef/webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/TracingController.scala#L183) sends a `409` error when version numbers to match. IMO the best thing to do, would be rephrasing the error message sent by the frontend to reflect the multiple causes of the issue.
Maybe you have better ideas @fm3 @philippotto :slightly_smiling_face:

**Comment by philippotto** [comment]
> IMO the best thing to do, would be rephrasing the error message sent by the frontend to reflect the multiple causes of the issue.

Yes, this should definitely be done. Nevertheless, I think, it would be still good to find out why this is happening in the first place. Can you open a pr which rephrases the error message? :)

**Comment by youri-k** [comment]
I think this happens because the fossildb with the old configuration sometimes ran blocking operations, that took some time. If the number of new write requests during these operations exceeded a certain threshold, the fossildb rejected new write requests and some updates got lost. After that new updates from the frontend had a different version than the one the fossildb expected and therefore got rejected. This phenomena looks very similar for the fossildb to editing a tracing in different windows simultaneously.
I hope the new fossildb configuration can prevent the update loss.
PR is almost open :D

**Comment by philippotto** [comment]
Thanks for clearing this up! So, the save requests are flushed asynchronously, which is why the front-end thinks that they were properly written to the DB, but in reality, they got lost. Is this correct? Can we make the save requests blocking in the back-end then?

**Comment by fm3** [comment]
I would have thought that they are 🤔 if they are not, it’s a bug.
