### ISSUE TITLE
Moving trees into groups seems broken in Firefox

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4283]
I couldn’t get my tree into a newly created group with drag’n’drop, works in Chrome

**Comment by MichaelBuessemeyer** [comment]
Sorry, I missed that issue. This is along time existing bug of the library used to render the trees as a hierarchical structure. Somehow all animations that work in chrome do not work in firefox.

But even without the animations, it is possible to move trees into groups but also kinda bothersome. For the gif, I used the current version deployed for mpg.
![moving-trees](https://user-images.githubusercontent.com/39529669/78138187-d3d8c700-7426-11ea-8db6-a15e3b0a3004.gif)

**Comment by MichaelBuessemeyer** [comment]
The only option I can think of to resolve this bug is to create a fork from the library and try to find fix the bug there.
But I think this is not a good idea as there have never been any complaints from our costumers about this bug. Almost all of them seem to use chrome. Thus it would a waste of time in my opinion.
@normanrz @philippotto What do you think about this?

**Comment by fm3** [comment]
Seems to be fixed in Firefox 87 both on Windows and Linux 🎉 (Did we change anything here recently? Or is it just the Firefox update?)
