### ISSUE TITLE
Drop support for knossos cubes

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4359]
We could do a lot of nice refactoring if knossos cube support is dropped. Like, we could get rid of the ElementClass concept in favour of voxelType + voxelSize.
First, let’s check in the databases if anyone still uses knossos datasets in wk.

**Comment by philippotto** [comment]
For backwards compatibility, it's probably nice to maintain knossos support, but maybe the backend could simply kick-off a cubing job instead of having the current adapter?

> voxelType + voxelSize.

Just a side note: we should use channel count instead of voxelSize (channel count = voxelSize / byteCount(voxelType)), since that's nicer to deal with in code, in my opinion.

**Comment by normanrz** [comment]
I think the support for knossos cubes can go. It is not 1-to-1 compatible anyway. And we have migrated all datasets afaik.

**Comment by hotzenklotz** [comment]
Related to #3511. Probably it is either this or the other one.

**Comment by fm3** [comment]
but add conversion guide to docs
