### ISSUE TITLE
Can we get rid of back-end NML parsing?

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4396]
Which use cases require the back-end to parse NMLs? How can we replace it with front-end side NML parsing?

**Comment by fm3** [comment]
The back-end NML parser is used in two general use-cases
 - upload n explorationals, to be merged into one
 - task creation from NML zip (one task is created per tracing in the zip. it’s also on the roadmap to support volume tracings too, see #4401)

I’d say the moving second one, task creation, would be a relatively complex change, since there is no other API for task creation that uses save requests (annotationBase is considered immutable). I’m not saying that this cannot be done, but I’m not sure it would be worth the effort, compared to maintaining both NML parsers. What do you think @youri-k ?
