### ISSUE TITLE
[Merger Mode] Add to toggle for hiding all unannotated segments

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#4398]
When in Merger Mode, it is sometime hard to see what is going on. Which segments did I already annotate and which still need work. 

It would be great to have a simple toggle to hide all segments that are not marked/affected by the merger mode (=which do not contain a node). Toggling between all segments and the annotated ones make it very easy to see wich areas require more work.

Related:
- ID mappings already have a `hideUnannotatedIDs` options. I assume, there might be a way to reuse this code/functionality for the feature
- Thinking larger: 
  -  Perhaps this feature need not be tied to merger mode directly. It could make sense to just always offer this toggle. Often, skeletons are used for marking segments (but not necessarily to connect them like in Merger Mode)
  - (Perhaps, this toggle is also interesting for volume annotations. Especially, if one is drawing over an existing segmentation, it might be nice to hide any segment not touched by the user in any way (=hide the Fallback layer?))

**Comment by MichaelBuessemeyer** [comment]
I'll split this into two PRs. The feature for the merger mode will be the first and the second will include the "Thinking Larger" parts

**Comment by MichaelBuessemeyer** [comment]
@hotzenklotz I talked to @philippotto about your suggestions.
The feature that will be added with #4510 allows the user to "hide all unmapped segments" but only when a mapping is active. This happens when you e.g. load a mapping from the server or use the merger mode to create one.

This is not directly what you wanted. At least that is how I understand your text.

In my opinion hiding, all segments that are not annotated within a skeleton tracing will not be straight forward. The same goes to volume tracings. 
If you only want to see the data the user annotated and not the fallback layer we need to change some things. Because currently the user just overwrites the loaded fallback layer. Therefore making it not possible to decide whether the current voxel is annotated or has the color of the fallback layer.

Is the feature described above and added with #4510 enough or shall we also try to add the "hide unannotated segments" feature for skeleton and volume tracings without any mapping data?

**Comment by hotzenklotz** [comment]
I wonder: Is the merge mode so much different from using mapping files? In both case, an existing segmentation is "remapped" to different IDs. I was hoping that both features sort of use the same code. From a users perspective the difference is only how the mapped segments are selected:
1) Either automatically through an ID entry in the mappings file
2) through a skeleton node

In both cases it would be nice to hide all segments that were not mapped/affected

**Comment by MichaelBuessemeyer** [comment]
@hotzenklotz That's exactly what is done in #4510 :tada: 

But when I read your "thinking Larger" part from above, I thought you also want this feature when no mapping is active.
One use case I can think of in case of skeleton tracings is that you might want to only see the segments that have a node. This would be kinda like the merger mode except that not all segments that are connected with the same tree automatically get mapped to the same id. Their original id will just be kept.
The other use case I could think of is when performing a volume annotation using a fallback layer. In this tracing, you might want to see what you annotated your self and not the fallback layer.

Both described cases would require some more deep work.

But if the two use cases you just named are enough, then #4510 will add the feature you want.

**Comment by hotzenklotz** [comment]
@MichaelBuessemeyer I see! I think the basic version is fine for now. Let's see how much this will be used. Than we can always expand on this. Thanks Micha.
