### ISSUE TITLE
Dataset list reorders when refresh request completes, leads to misclicks

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4461]
when navigating to the dataset list, frontend-cached datasets are immediately displayed, but an asynchronous request to the newest list is sent to the server. when that request completes, the list is reordered. this leads to misclicks if the user points their mouse while still seeing the old list.
Let’s discuss how this can be improved

**Comment by philippotto** [comment]
I have multiple ideas:

- **Only show "important" updates:** At the moment, the async refresh can change two things: the *set* of datasets and the *order* of the datasets. The order changes quite often due to our LRU logic. We could simply check whether only the order changed, in which case we wouldn't show the update, since the order is not that important.
- **Don't show any updates unless requested:** The "Refresh" button is used quite often, anyway (at least in our team). If the user cannot find their dataset, they will probably use it. So, doing the async refresh to update the cache (but **not** to update the UI) might be a valid choice.
- **Show an explicit update indicator:** We could tell the user that an async update is in progress and once it is finished, the indicator could turn into a button saying "Show 5 new datasets available". Similar to this picture: https://i.stack.imgur.com/cWkTc.png

While we are at it, we could also clean up the loading indicator of the async refresh. Currently, that's simply using the loading indicator of the "Refresh" button but this is semantically wrong, since that button does a different kind of refresh.

**Comment by fm3** [comment]
Just for completeness, I’d add an even simpler fourth idea: discard the user-side cache entirely and show the list only when the data is fetched. It stems from times when the refresh request took ~25s.

However, that one would possibly slightly degrade user experience, with the user having to wait longer before being able to do anything.

I think all of your ideas are valid (also not mutually exclusive). I like the update indicator, which would of course only show up in case of changes in the _set_ of datasets. But that one also seems to be the biggest change. I think that the first idea (only show important updates) has the best work-to-UX-benefit ratio.
