### ISSUE TITLE
How to stream NML files from the data server to wK

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4474]
time and again we generate NMLs on the server only to download them locally, then drag them into a wK tracing. Can we create a more direct way to get NMLs into wK?
idea 1: NML directory automatically mapped to individual annotations in your account
idea 2: a button in your tracing view gives you a URL to paste to a command on the server that will stream your NML directly into the open tracing via websockets

**Comment by philippotto** [comment]
> idea 1: NML directory automatically mapped to individual annotations in your account

I just had a slight adaptation of this idea. If you are the "owner" of a dataset, it could make sense, to simply add the NML file to that dataset directory (I think that covers 95% of the usecases). When you open such a dataset, the info tab in wk could show the "attached nmls". When you click on such an NML, the back-end creates a new tracing using that NML and switches to that annotation (if the user has done so before, this could be mapped to the already created annotation).

The advantage of this approach is that we wouldn't need to have "user directories" (which I imagine a bit cumbersome, since it's an additional folder hierarchy on disk). The disadvantage is that you have to mutate (append to) dataset folders. But we do this constantly anyway.

What do you think?

**Comment by philippotto** [comment]
> The disadvantage is that you have to mutate (append to) dataset folders. But we do this constantly anyway.

Hm, okay, on a second thought I'm not too sure about this. If we have a voxelytics task which only creates an NML, it might be weird to add that to an existing dataset folder.
Another version of this idea could be to have a folder structure likes this:
```
Datasets
  Dataset_A
  Dataset_B
  NMLs
      Dataset_A
        some_trees.nml
```

Then, one doesn't need to "fear" to mutate something. But I'm not too sure whether this is really cool. Probably simpler to do this via users:
```
Datasets
  Dataset_A
  Dataset_B
  NMLs
      User_X
        some_trees.nml
```

**Comment by philippotto** [comment]
Since was brought up again by @jstriebel, maybe we could provide a simple HTTP endpoint to which one can push an NML file? Maybe this is already possible with the existing upload route? Each user would probably need to configure an auth token for this, but that might be alright.

**Comment by fm3** [comment]
Yes, you could try that. Compare https://docs.webknossos.org/reference/rest_api#post-annotations-upload

**Comment by philippotto** [comment]
@jstriebel We discussed this feature in our sprint meeting and think that this should be possible by using the existing upload route via HTTP (see the link @fm3 posted). Could you give this a try when you need this feature again and report here? Thank you :)

**Comment by jstriebel** [comment]
@daniel-wer took over this feature for voxelytics

**Comment by daniel-wer** [comment]
Fixed in https://github.com/scalableminds/voxelytics/pull/1912
