### ISSUE TITLE
Default dataset configuration immediately copied to user account?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4481]
Quote @youri-k in https://github.com/scalableminds/webknossos/pull/4357#issuecomment-599611208:  

> When you open a new dataset, you get the current dataset default configuration, and instantly respond to the server with this default config as your new user config. When the default config changes afterwards, you won't notice the change because your user config takes precedence. I don't know if this intended, but it's the same on the master. My feeling would be to only save a new user config, if the user actually changes his dataset settings and not just copying the default config at the point of first opening the dataset.

Let’s discuss what the desired behavior would be (also maybe document the entire precedence structure somewhere, as it has become quite involved already)

**Comment by youri-k** [comment]
This behavior is intended because not copying the default configuration could lead to unexpected changes when opening the dataset multiple times.
The precedence structure is now explained in the [documentation](https://github.com/scalableminds/webknossos/blob/master/docs/datasets.md#view-configuration-hierarchy).
