### ISSUE TITLE
Isosurface route does not support agglomerate mapping

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4509]
The front-end sends requests like this:

```
{"position":[200700,194940,3580],"cubeSize":[260,260,260],"zoomStep":1,"segmentId":1483607019,"mapping":"agglomerate_view_65","voxelDimensions":[4,4,4]}
```

and the back-end throws an error, since it probably expects a JSON mapping. Ask me for a link to reproduction.

**Comment by fm3** [comment]
Do you think the frontend could be modified so that it also supplies the mapping type (hdf5 vs json) in the request? Of course we could check which exists in the backend, but that would be another IO operation (or an additional cache) so it may impact performance. If this is a simple change in the frontend, I’d think it’s the better solution
