### ISSUE TITLE
Expose min/max for float layers

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4526]
With float layers the histogram is necessary for any viewing of the dataset. Sometimes the sampling does not yield sensible results. For these datasets, it would be nice to specify min and max with an input field. Please note that the range of floats can be both very small (e.g. 4.8e-15) and very large (e.g. 3.2e+12).

**Comment by philippotto** [comment]
Additional (opinionated) notes:
- the input fields should be validated against the valid value range of the layer (e.g., only 0-255 should be allowed for uint8)
- using `parseFloat` will automatically parse scientific notation (e.g., 4.8e-15). an UI hint could tell the user so (if we find space for that hint)
- the fields should only be visible after the user clicks an "edit" button, in my opinion. showing these fields all the time for all layers adds too much clutter, otherwise
