### ISSUE TITLE
Volume segmentation copy shortcuts are flipped under certain conditions

### ISSUE THREAD

**Issue by cnzqy1** [scalableminds/webknossos#4708]
Under certain conditions the functionalities of keyboard shortcuts `V` and `SHIFT + V` are flipped, i.e. `V` copies from the next slice and `SHIFT + V` copies from the previous slice instead. One way of reproducing this:

(d/f Switching option disabled, and volume segmentation exists in slice 1)

1. Navigate to slice 2 and press `V`. The volume annotation from slice 1 is copied as expected.
2. Erase the volume annotation in slice 2 using the brush mode.
3. Navigate to slice 1 and change the segmentation in some way by painting or erasing.
4. Navigate to slice 2. Pressing `V` now does not do anything, and pressing `SHIFT + V` copies the volume segmentation from slice 1 instead.

The procedure above is obviously an artificial situation, but I have encountered the same bug under conditions that are probably related. Similarly, under certain conditions I need to use `V` instead of `SHIFT + V` to copy from the next slice.

**Comment by philippotto** [comment]
Thank you for this report! This definitely sounds like a bug. We will investigate this. The way it's currently implemented is that the current "move direction" is taking into account so that copying from the "previous" slice can be z-1 or z+1. However, there seems to be a bug in the direction logic.

By the way, right now, this feature is independent of the d/f switching option, but maybe it makes sense to hook this together. Then, disabling d/f switching would make the feature very transparent regarding the source of the copy operation (V would always take the source from z-1 and Shift+V would always use z+1). Do you think this makes sense? Will also discuss this internally.

**Comment by cnzqy1** [comment]
Thanks for your reply! Yes, I think linking the d/f switching option with this feature makes a lot of sense (I originally thought this was the case).

**Comment by MichaelBuessemeyer** [comment]
@cnzqy1 The results of my analysis are that turning the `d/f switching option` option is not considered when copying a slice (just like @philippotto already mentioned).

With PR #4728 the option `d/f switching` will be taken into account when copying a slice. Thus if `d/f switching` is turned off the "previous" slice will always be -1 and the "next" slice will always be + 1.


Just mentioning:
What you posted isn't actually a "bug" in the calculation of the "move direction" and is expected behaviour if `d/f switching` is turned on. 
Here is the reason why: 
The current "move direction" is the vector between the two last annotated slices. Thus if you annotate in slice 2 (step 2) and then move up to slice 1 and annotate something there (step 3) the "current move" direction will be negative in the `z` direction. This is what caused the "flipping" between `v` and `shift + v`.
-> Nevertheless, the setting of option `d/f switching` was being ignored which shouldn't be the case here
