### ISSUE TITLE
Histogram float range should show decimal places

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4753]
if the dataset brightness range is from 0.0 to 0.1, both the tooltip and the text boxes should support inputting and displaying the appropriate values

**Comment by philippotto** [comment]
Reassigning this to @grittaweisheit to distribute the workload a bit :)

**Comment by normanrz** [comment]
Unfortunately, this #4802 doesn't solve the issue, because 2 digits are not enough. 

Example:
<img width="344" alt="Screenshot 2020-10-01 at 10 14 12" src="https://user-images.githubusercontent.com/335438/94784806-f8f6c400-03ce-11eb-8394-1ae3e3d59eb9.png">
This dataset has a dynamic range of 0.000350447662640363 to 0.00003167275644955225. I want that visible/editable both in the inputs and tooltips.

**Comment by philippotto** [comment]
@grittaweisheit Could you have a look at this again? :)
