### ISSUE TITLE
Half-selected group shows as empty

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4788]
When only a few trees in a group are selected, the group is shown as unselected. With collapsed and deeply nested groups, it becomes extremely difficult to find the selected tree. It would be great to have an indeterminate state:
<img width="169" alt="Screenshot 2020-08-28 at 13 45 35" src="https://user-images.githubusercontent.com/335438/91557443-c4f23400-e934-11ea-9d2c-005235ae55a0.png">

<img width="169" alt="Screenshot 2020-08-28 at 13 42 49" src="https://user-images.githubusercontent.com/335438/91557347-a12eee00-e934-11ea-8614-ab9f139dbcdc.png">

**Comment by philippotto** [comment]
:+1: 

Somewhat related: The "indeterminate" state could also be used for empty groups. Currently, the visibility of empty groups cannot be changed, as that information is derived by its children (since there are no children, the user cannot change that). Right now it defaults to "checked", but "indeterminate" might fit better.
