### ISSUE TITLE
Loading histogram blocks data loading

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4829]
I did not check the code, but it looks to me like loading the histogram blocks the first bucket data loading requests in the front-end. However, histogram loading may be slow (especially in remote wk-connect datasets, when https://github.com/scalableminds/webknossos-connect/pull/96 is merged). Could it be changed so that data-loading starts faster and the histogram is loaded later? I realize that for float layers the histogram min/max values are required to calibrate the data range, but maybe it can be initialized with something heuristically and then be reset when the histogram request completes?

**Comment by grittaweisheit** [comment]
It seems the problem is that the histogram requests are all sent before the data request. And because browsers have a maximum number of request they handle, the data requests can get blocked by the histogram requests. 
One solution can be to send the histogram request sequentially, as implemented in [this PR](https://github.com/scalableminds/webknossos/pull/4861).
