### ISSUE TITLE
Allow to toggle empty tree groups

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#4858]
In the "Trees" tab, it seems that empty tree groups are always checked and cannot be unchecked:
![Screenshot 2020-10-08 at 14 28 05](https://user-images.githubusercontent.com/1701960/95458597-a4c18600-0972-11eb-838c-8b2ae502533f.png)

Is there a good reason for it?

I usually look at tree groups one by one, first toggling off all and then on what I want to look at. In this case, it takes a second which one is currently visible because all empty groups are also checked.

**Comment by philippotto** [comment]
> Is there a good reason for it?

The reason is purely implementation-specific. We don't store the visibility for groups. Instead, the visibility of groups is derived by looking at the visibility of their children. Therefore, the visibility of empty groups always defaults to `true` (we could change it to `false`, but I guess, that this doesn't solve your problem).

I guess, we have to think about how to store the visibility information explicitly.

**Comment by georgwiese** [comment]
OK cool, that makes sense.

One more thought: seems like if any child is toggled off, the parent is also. Therefore, you can't see which groups have toggled-on children. Perhaps it would be best to have a "half toggled" state to indicate that some children are on and some are off.

**Comment by philippotto** [comment]
> One more thought: seems like if any child is toggled off, the parent is also. Therefore, you can't see which groups have toggled-on children. Perhaps it would be best to have a "half toggled" state to indicate that some children are on and some are off.

Yes, definitely. This idea is also covered here: https://github.com/scalableminds/webknossos/issues/4788
I'll try to get this tackled soon :)
