### ISSUE TITLE
Volume undo doesn't work properly sometimes?

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4921]
I used the fill-tool to fill the entire viewport (in mag 2). When hitting undo, the majority of the data was restored successfully, but the outside border wasn't for some reason. The final output looked like this:

![image](https://user-images.githubusercontent.com/2486553/98531414-966fce00-2280-11eb-8d15-e68751a9dce0.png)

When zooming in, the segmentation also looked a bit different:
![image](https://user-images.githubusercontent.com/2486553/98531540-c3bc7c00-2280-11eb-8eb5-c4562f5435b7.png)

**Comment by MichaelBuessemeyer** [comment]
I tried to reproduce this bug but was unsuccessful. 

Even putting wk under some stress by doing a fast mixture of annotation and undo could not reproduce this :/ 

Nevertheless, I noticed that a big annotation step might take some time and the undo speed between bucket annotations being undone is not consistent.
Maybe this is due to a race condition :thinking: 

If this happens again, please try to write down what you did so we can find a way to reproduce this

**Comment by philippotto** [comment]
For the record: This probably happened because too many buckets were processed, so that some had to be released to stay within the limits exposed by RAM. This issue should be somewhat mitigated as we reduced the worst-case resource-overhead of annotating large areas (by limiting possble mags the volume annotation tools can operate in). Let's reopen when/if we see this issue again.
