### ISSUE TITLE
Importing mesh in view mode doesn't work

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4935]
How to reproduce:
- Open this dataset https://webknossos.org/datasets/scalable_minds/l4dense_motta_et_al_demo/view#2850,4318,1770,0,1.000
- Open `Meshes` tab
- Import this mesh: 
[5918_simplified.stl.zip](https://github.com/scalableminds/webknossos/files/5523486/5918_simplified.stl.zip)
- Boom 
<img width="1552" alt="Screenshot 2020-11-11 at 11 38 36" src="https://user-images.githubusercontent.com/335438/98801955-debef580-2412-11eb-94dc-d453b16f0e2b.png">

**Comment by philippotto** [comment]
Related: this error only appears in a very obscure report in airbrake: https://scm.airbrake.io/projects/95438/groups/2835680766133594723?tab=notice-detail

Instead of `[object Object]`, there should be a proper error message. I suggest to investigate this, too, before fixing the actual problem, since it's crucial to have robust error reporting.
