### ISSUE TITLE
volume annotation’s largest segment id is never bumped from 0 to 1

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4937]
when opening a new volume annotation (no fallback layer) and brushing some, there is no update action setting the largest segment id to 1, even though there is now data with segment id 1.
this leads to wrong id remapping when importing a volume data zip.
when creating more cells later the update actions setting the largest segment id to 2, 3, etc are sent correctly

**Comment by daniel-wer** [comment]
I found the issue, but am wondering what the best fix would be. It's a combination of three things.

First of all, the frontend always needs an activeCell which is why one is created automatically when creating a new volume tracing. Secondly, this is hidden from the diffing to avoid always having an unsaved state when creating a tracing. Thirdly, the largest segment id is immediately updated when creating a new cell (using "C" or the "Create Cell" button). Strictly speaking, this should only happen once the user annotated at least one voxel using the new cell id.

I feel like the proper fix would be for the frontend to only create a new cell in a new tracing, once the user annotates the first voxel. This would mirror the behavior in skeleton tracings where the first tree is only created once the first node is set. This would be a bit of work as there are quite a few spots which assume there always is an activeCellId.

Alternatively (or in addition) the largest segment id could be updated only once a voxel using that id was annotated. This would lead to cases where the activeCellId is larger than the largestSegmentId, though, not sure whether that is problematic/unintuitive.

Any opinions? (/cc @philippotto)

**Comment by philippotto** [comment]
> [...] the largest segment id could be updated only once a voxel using that id was annotated. This would lead to cases where the activeCellId is larger than the largestSegmentId, though, not sure whether that is problematic/unintuitive.

This sounds like a fair approach to me. In general, the user is probably not aware of the largest segment id, anyway, since we only use that to be able to create a fresh id. The only downside I see is that hitting "create cell" multiple times will only bump the id once (since the user didn't label anything and thus didn't bump the id). That's a bit counter-intuitive probably. Two possible solutions come to my mind for this, though:

- Disable the button if activeCellId > largestSegmentId. A tooltip could explain that the id wasn't used yet. However, this also feels quite weird to me. First, because one can still set the ID arbitrarily in the settings. Second, hitting C to cycle through the available "colors" (as I sometimes do :D) wouldn't be possible. Three, we already have a lot of tooltips :laughing: 
- Create cell generates `Math.max(activeCellId, largestSegmentId) + 1`.

I like the second option better. Not sure if there are any major downsides other than being a bit hard to understand (however, the user shouldn't really have to care about it, anyway).

> This would be a bit of work as there are quite a few spots which assume there always is an `activeCellId`.

Is it still quite some work with the above approach of allowing `activeCellId > largestSegmentId`?

**Comment by daniel-wer** [comment]
> I like the second option better. Not sure if there are any major downsides other than being a bit hard to understand (however, the user shouldn't really have to care about it, anyway).
> 
> > This would be a bit of work as there are quite a few spots which assume there always is an activeCellId.
> 
> Is it still quite some work with the above approach of allowing activeCellId > largestSegmentId?

I favor this option as well and I don't think allowing activeCellId > largestSegmentId should pose any problems in the frontend.™
