### ISSUE TITLE
Largest segment ID

### ISSUE THREAD

**Issue by Pablo1990** [scalableminds/webknossos#4974]
Hi!

Thank you for this amazing platform. I have just converted both my raw data and segmented one to WKW format and uploaded it to the platform correctly. However, at the end of the process (just before starting to use it), it asks me for the 'largest segment ID', which should be lower than 256. Usually, my tissues have from 1000 to 2000 cells, are you planning in the future to increase this number? I can do ROIs, but it is not ideal at all.

Thank you for your time.

Kind regards,
Pablo

**Comment by philippotto** [comment]
Hi Pablo!

thank you for giving webKnossos a try! We support multiple data types, including uint8, uint16 and uint32. Therefore, having 2000 cells is definitely possible.

Did you use [wkcuber](https://github.com/scalableminds/webknossos-cuber) for the conversion? By default, the cubing process assumes a dtype of uint8 which would explain your troubles. If you convert the segmentation data using `--dtype uint16` (or `uint32`), you should be able to set the correct "largest segment ID".

Can you confirm that this solves the problem? We will try to improve the import process so that these errors cannot happen that easily.

Thank you for your patience,
Philipp

**Comment by Pablo1990** [comment]
Hi Philipp,

Thank you for your quick answer! Yes, it did solve the issue. I can now see both my 'color' and 'segmentation' channels, still when trying to correct them. But now I keep getting an error of 'failed to create annotation'. Here, I have done but did not work either:
- Put both 'channels' to uint16 (color is initially 8-bit)
- Try to put the highest possible number of cell if that could be an issue (I tried several but end up with 64000, which I am sure I do not have it as an ID).

I attached the console errors:
<img width="534" alt="Screenshot 2020-12-04 at 09 38 40" src="https://user-images.githubusercontent.com/1974224/101147665-96ab8100-3614-11eb-950a-b7c9d75c7909.png">

Let me know if you need more information on the issue.

Thank you very much again for your help.

**Comment by philippotto** [comment]
Cool, we seem to have gotten one step closer to get it working!

Can you open the dataset in view-mode (i.e., by clicking "View")? I validated your dataset, but couldn't find an issue with it. So, I'm not sure what is causing this error. I'll also ask some colleagues about it and let you know once I got some insights.

**Comment by Pablo1990** [comment]
Yes! It is when I click on 'Create annotation' -> 'Using existing segmentation', I got the error I mentioned before
<img width="1442" alt="Screenshot 2020-12-04 at 12 09 42" src="https://user-images.githubusercontent.com/1974224/101162025-ada89e00-3629-11eb-8bad-200e4789a951.png">

Thank you so much for taking into consideration and for your time!

**Comment by philippotto** [comment]
Alright, I've got new insights. The story is a bit complicated, but bear with me. There are three possible solutions:

(a) Go to your dataset dashboard, click "edit" for the dataset in question. Switch to the "Sharing & Permissions"-tab and select a team for the "Allowed Teams" (probably named "Default").
Explanation: This is merely a workaround for a bug we just found. Normally, the uploader of a dataset should also have the permission to create annotations for it. However, this is not handled properly at the moment.

(b) Alternatively, you can wait until we fixed the above bug (should be deployed on Monday probably).

(c) Log out & create a new account. Re-upload your dataset there and you are good to go. Note that you currently need to use another email address, since our organization and user concept demands unique email addresses. We will rework this concept very soon, but for now you have to use another email address. If this poses a problem for you, let me know and we can work out another solution.
Explanation: Creating a new account (without an invitation link) will create a new organization in which you will be the admin (and only member). Then, you don't need to set any "Allowed Teams", since you are admin (and for that case the aforementioned bug does not exist).

And now a bit of context and important information:
Since you created your account for the webKnossos workshop this week, you are in the same organization as all other users who participated in the workshop. All participants were granted the role of "Dataset Manager" so that you can upload your datasets. However, this also means that your dataset can be seen by all other dataset managers. If this is a privacy problem for you, you should delete your datasets and go with the above option (c). Creating your own organization will also have the additional benefit that you can easily invite other collaborators and have more powers to administrate webKnossos.

Let me know in case something doesn't work out or if you have further questions!

**Comment by Pablo1990** [comment]
Thank you so much for your help and explanation! I have created a new account and now I can create volume annotations! I will keep using it and let you know with further questions/problems!

Best,
Pablo
