### ISSUE TITLE
Mesh shading looks weird

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5011]
The shading/lighting of imported meshes looks weird; as if there are multiple colors blended in:
<img width="850" alt="Screenshot 2020-12-29 at 11 28 50" src="https://user-images.githubusercontent.com/335438/103277319-0836df00-49c9-11eb-87a6-ecfe067696d2.png">

**Comment by MichaelBuessemeyer** [comment]
@normanrz My specific task here is what exactly? To change the shader / the way the mesh is rendered?
As far as I can remember we had the idea of doing this iteratively and that the first version should be quite simple. As I can remember you already had something in mind for that, right @philippotto?

Just some comment:
My guess why the shading looks this way is because the normals are rendered for the mesh. (See [Normal Mapping](https://en.wikipedia.org/wiki/Normal_mapping#/media/File:Normal_map_example_with_scene_and_result.png)).

**Comment by normanrz** [comment]
The shading of the on-demand rendered meshes is good. I think the uploaded meshes should be shaded in the same way. Ideally, each uploaded mesh would get its own color (maybe cycle through the tree color list?).

**Comment by philippotto** [comment]
>  As I can remember you already had something in mind for that, right @philippotto?

Yes, that's what I meant:

> The shading of the on-demand rendered meshes is good. I think the uploaded meshes should be shaded in the same way.

**Comment by MichaelBuessemeyer** [comment]
For the record: The "on-demand rendered meshes" are the rendered isosurfaces.

**Comment by normanrz** [comment]
> For the record: The "on-demand rendered meshes" are the rendered isosurfaces.

They are both "meshes" and both "isosurfaces" ;-)
