### ISSUE TITLE
NUX: Add UI hints to show features

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5022]
For new users (or new features), we could show UI hints (e.g., popovers) to explain some important features. This can be useful to guide users during (or after) onboarding through the most important steps. For example, after the account was created, one could nudge the user to import a dataset or to start an annotation.

When we add new features, we could also add such UI hints to present the feature to users.

In general, we probably want to store a boolean for each user and for each "feature" to remember whether the user has already cancelled the NUX.

nux == new user experience

- [X] gather nux-worthy features:
  - short tour/tutorial to explain wk core UI
  - new "meshes" tab with isosurface list (only when there is a segmention)
- [x] have a look at announce kit
- [x] implement

**Comment by philippotto** [comment]
@daniel-wer researched this bit and found the promising-looking library https://shepherdjs.dev/. I'd suggest to give this library a try and test out the following stuff:

- build a dummy tour for the tracing view ((1) this is the toolbar, it can do this and that (2) these are the tracing viewports etc...)
- highlight some new feature (e.g., the overhauled meshes tab)

This doesn't necessarily need to be very polished. I'm primarily interested in how easy the integration is and what kind of UX impression this would have.

Might be something for @MichaelBuessemeyer when he has free capacities :)

**Comment by MichaelBuessemeyer** [comment]
Ok here are my thoughts/findings about the library:
First, this lib looks nice and could be a good solution. Additionally, it looks like it is pretty easy to use. 
However, the lib supports multiple js frontend frameworks and has specialized versions for them. The same goes for React. But I could not get the react version working correctly for quite some time. One reason might be, that the react version only supports hooks and not the "usual" react way of handling a components state.

Therefore I just stopped trying to use the react version and moved to the "normal" version. The normal version worked out of the box and I was able to create a small tutorial within a short time period.
Note: Everything is built for the OthroView mode. Other view modes might crash.

My first thoughts on what we need to change:
- To directly hint at an element, this element needs a unique css class or id. Therefore components we want to hint at would need a small but easy change.
- To show the user the newest features since his last visit, I suggest the following for the tracing view:
  - We need to maintain a single js file containing an array of steps hinting at the newest features in chronological order. This would be like a changelog.
  - Each user has an id or index of the last seen update hint of that list saved in the db.
  - Each time the user opens the tracing view the frontend checks whether the user has any pending new features to be hinted at.
  - If the user has pending hints, a new button with a blub or so could appear in the navbar on the left side of the user avatar button. When this button is clicked, the new pending updates will be shown to the user.
  - After the new features tour, the index value saved in the backend updates, so the user is not bothered each time.

I just pushed a branch that has a tour in the tracing view that is always triggered when a tracing is loaded and the option to show new features by clicking a button in the right corner of the navbar.


Thoughts about problems we will have:
 - If we want a good tour, we would need to explain each tab. Therefore we need a way to make a defined tab visible, but I already tried this in #4918 and this was quite tough and clunky with golden layout.
 - To be able to interact with the tracing we, the tour sometimes needs to change the state of the tracing view. This would mean to have all the steps inside the tracing view component or to bind the context. I tend to the second option to keep the tracing view component clean.

**Comment by philippotto** [comment]
> Therefore I just stopped trying to use the react version and moved to the "normal" version. The normal version worked out of the box and I was able to create a small tutorial within a short time period.

Bummer! Did you find an issue/bug report in their repository? You are probably not the first one to have issues with this :thinking: 

> I just pushed a branch that has a tour in the tracing view that is always triggered when a tracing is loaded and the option to show new features by clicking a button in the right corner of the navbar.

Cool, I just checked it out and it feels pretty good already. Styling and content would need some iterations, but overall this looks very promising.

> Each user has an id or index of the last seen update hint of that list saved in the db.
Each time the user opens the tracing view the frontend checks whether the user has any pending new features to be hinted at.

In #5099 we added an `novelUserExperienceInfos` object to the user where we can store such information in a key/value manner. The key specifies the step or feature and the boolean signals whether the user has already seen it. I think, this is a bit more granular than a timestamp.

> - If we want a good tour, we would need to explain each tab. Therefore we need a way to make a defined tab visible, but I already tried this in #4918 and this was quite tough and clunky with golden layout.
> - To be able to interact with the tracing we, the tour sometimes needs to change the state of the tracing view. This would mean to have all the steps inside the tracing view component or to bind the context. I tend to the second option to keep the tracing view component clean.

For a first tour version, it's probably alright to keep things as simple as possible. Showing elements which are always visible (navbar, settings button, viewports, maximize-icon etc.) is already a major improvement over not having a tour at all. Also, we should try to keep the tour quite snappy and only include the most important stuff.

I suggest to discuss the next steps for this issue in our next sprint meeting. Thanks again for doing the spike :tada:

**Comment by MichaelBuessemeyer** [comment]
> Bummer! Did you find an issue/bug report in their repository? You are probably not the first one to have issues with this 

No I could not find a issue for this. My main problem was the missing documentation about how to use the react version. There exists only a single example using hooks and looking at the lib, you can only use hooks when you use the react version.

What I really dislikes is that the react version requires an empty functional component, that saves the tour's state and does nothing more 🤷‍♂️. By using the normal variant I was able to manipulate the state of the tour more easily.

> edit: but maybe it's ok, to use html ids here.

Using html ids / classes is always required, independent of the version to attach a step to an html element..

> the extra level of indirection gives us the possibility to define the tour at a central place (which wouldn't be possible otherwise probably?).

In my opinion (I did not try it out) both version are equally "powerful" when it comes to where define the tour.

> Thanks again for doing the spike 🎉

Sure, it was fun 😸

**Comment by MichaelBuessemeyer** [comment]
@philippotto We already have a "What's new" Popup right? I thin it was introduced in this pr #5665.

Thus as we turned away from this idea, can we close this issue?

**Comment by philippotto** [comment]
> Thus as we turned away from this idea, can we close this issue?

Yes, good point :+1: We might want to do a proper "tour" at some point, but we can open another issue then (as the current one has a broader scope which is already tackled).
