### ISSUE TITLE
Provide checkbox (+ shortcut) to disable tree rendering

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5069]
One can already toggle the visibility of all trees, but this often mutates the existing visibility-checkboxes. It would be cool to have a shortcut (and menu item probably) which simply enables/disables the tree rendering (by passing a boolean to the node and edge shaders). Then, the behavior should be quite similar to the `3` shortcut which toggles segmentation visibility.

Note: if the tree rendering is disabled, there should be a UI hint (e.g., in the viewport status indicator). Otherwise, it could happen that users are wondering why no trees are rendered. Showing some UI hint in the trees tab would also be imaginable.

**Comment by hotzenklotz** [comment]
@MichaelBuessemeyer Please take note. Looks like this issue will be covered by the new "Skelton" layers, right? If so, please close as duplicate or once the PR is merged.

**Comment by philippotto** [comment]
Just as a side note: As far as I know the current state of the PR in question mutates the visibility-checkboxes, which should not happen in accordance to this issue.

**Comment by MichaelBuessemeyer** [comment]
In the current version of #5384 the skeleton layer simply toggles all tree-visibilites, just like @philippotto said.

But I think adding the option to simply not render any skeletons via a scene controller setting and not to toggle the visibility of all trees is better imo. Because this enables the users to temporarily hide all skeletons but does not change their visibility state. Therefore it possibly saves the user quite some time, if she/he wants to see only some selected trees. If the user now uses the "hide all skeletons toggle" of #5384 the user needs to hide all unwanted trees again after making all the trees visible again.

Additionally, the use-case of toggling the visibility of all trees is already implemented in the trees/skeleton tab.

What do you think about the arguments above @philippotto, @hotzenklotz? I would prefer to change the code in #5384 to hide all trees via a setting in the scene controller and not via toggling the visiblity of all trees and therefore possiblity saving some users some time and visiblity-clicking pain.

**Comment by philippotto** [comment]
> What do you think about the arguments above @philippotto, @hotzenklotz? I would prefer to change the code in #5384 to hide all trees via a setting in the scene controller and not via toggling the visibility of all trees and therefore possibly saving some users some time and visiblity-clicking pain.

Yes, that's what I was trying to suggest basically :) If you could attach the new skeleton-switch to a boolean in the scene controller so that the visibility of the trees can be controlled independent of the per-tree-checkbox, this issue here would be solved :+1:

**Comment by hotzenklotz** [comment]
@philippotto As far as I can tell this issue is fixed with the `skeleton` layers concept and the visibility toggle there, right? Closing issue for now.
