### ISSUE TITLE
Introduce Finished state for Explorative Annotations?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5087]
When publishing annotations, you do not want to accidentally edit them again later.

The current Finished state is really "Archived". We should rename it to make this distinction. The new "Finished" state should make it read-only, but it should still be in the normal annotation list.

**Comment by philippotto** [comment]
From our discussion:

- (potentially, rename "finished" state to "archived". however, maybe we can also keep it as is. especially, since "archived" wouldn't be a perfect fit for tasks.)
- add a "lockedByUser" (naming up for debate) property to the annotation object. only the owner should be able to mutate this.
- update actions for layers of an annotation will be rejected if lockedByUser is true
- the front-end should show locked annotations as "read-only" in the dashboard (look into how other read-only annotations are rendered)
- a tooltip should explain the reason
- opening an annotation that is read-only, should render as such with an explanation
- for the owner, the possibility to change read-only could be:
  - everywhere where "read-only" is rendered (e.g., in a popover)
  - for not locked annotations, the dropdown menu in the annotation view should allow to do the locking

Two questions I just had:
- Can an annotation layer be referenced by multiple annotations? If so: What happens if one annotation is locked, and the other annotation is mutated that references the same layer? Ideally, this should not be allowed.
- Changing the metadata of an annotation should still be allowed, even when the annotation is locked, right? Otherwise, one wouldn't be able to unlock it. Or should the locked property be the only exception for that? If all meta data can be edited, the UI should explain well that the locking only refers to the actual content of the annotation.

**Comment by fm3** [comment]
> Can an annotation layer be referenced by multiple annotations? 

Please don’t do that :D  (With the current data model, you can’t, since it’s actually the annotation layer that references exactly one annotation)

> Changing the metadata of an annotation should still be allowed, even when the annotation is locked, right? Otherwise, one wouldn't be able to unlock it. Or should the locked property be the only exception for that? If all meta data can be edited, the UI should explain well that the locking only refers to the actual content of the annotation.

Good question, I have no strong preference here. Maybe the locked boolean should really be the only thing, that would certainly be easier to explain to users.

**Comment by MichaelBuessemeyer** [comment]
> Good question, I have no strong preference here. Maybe the locked boolean should really be the only thing, that would certainly be easier to explain to users.

I think that is a good approach. In case some metadata needs to be edited, the owner can unlock it, change the metadata settings as wanted, and then lock it again
