### ISSUE TITLE
More space for mapping names

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#5146]
## Detailed Description

Currently, the width of the mapping names is fixed, so long names cannot be seen fully:
![Screenshot 2021-02-08 at 11 58 29](https://user-images.githubusercontent.com/1701960/107210925-1edb4780-6a05-11eb-89d4-0b222ffec633.png)

It would be great to solve this, e.g. by increasing the width, enabling scrolling, or adding line breaks.

## Context

Compare different mappings and view them in WK.

**Comment by fm3** [comment]
related to #4928

**Comment by fm3** [comment]
I’m afraid this issue could still be relevant, the menu has been moved to the left sidebar, but it still has the problems described above for long mapping names. They are somewhat alleviated by the mouseover title text, but my guess is that working with long mapping names is still a pain.

Feel free to re-close if you think the priority of that is too low, though.

**Comment by hotzenklotz** [comment]
> I’m afraid this issue could still be relevant, the menu has been moved to the left sidebar

The left side-bar is a fixed width and the mapping names already span the whole width of that. So there is no easy mappings only solution for making them wider. There is any issue to make the left-hand sidebar resizable #https://github.com/scalableminds/webknossos/issues/5302

IMHO, the fix is to to make the left-hand sidebar resizable (#5302) and not do a niche solution for the mapping dropdown.

**Comment by fm3** [comment]
sounds fair
