### ISSUE TITLE
Many user bounding boxes slow down tracing UI

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5188]
## Context
We could reproduce very slow UI responsibility in annotations with large numbers of user bounding boxes. The annotation of the initial report had 11319 user bounding boxes. Removing those from the NML and re-uploading made the UI run smoothly again.

## Expected Behavior
UI should remain smooth despite 10k user bounding boxes (we can a million nodes, this can’t be that much harder, right?)

## Current Behavior
UI becomes very slow to respond (including the top bar menus, even when not moving around. Data was still loading)

## Steps to Reproduce the bug
- Create NML with 10k user bounding boxes, drop into wK (or open the existing annotation from https://discuss.webknossos.org/t/msem-tracing-slows-down-everything/1643 )
- Try to move around, use menus

## Your Environment for bug
Windows 10, Chrome, Firefox, experienced by multiple users

**Comment by philippotto** [comment]
I had a short look at the performance behavior and the culprit seems to be the HTML representation in the sidebar (not the webgl context). Rendering 10k bounding box UIs (à 10? HTML elements) is probably simply too much to handle. We would need to employ a virtualized rendering strategy (as we do for trees) to cope with this.

However, I think, the important question is why are there so many bounding boxes in the first place? They are basically 99.9% duplicates. If wK produced these somehow, we should fix that. If they were produced outside of wK, I'm not sure whether we should do anything about it. Maybe warn about the high count? Optimizing performance for this very rare use case doesn't seem worthwhile right now.

**Comment by philippotto** [comment]
Closing in favor of #7938.
