### ISSUE TITLE
Toggling between two slices does not visibly move other viewports

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5233]
## Context
Viewing a dataset, toggling between two adjacent slices (either by alternating d/f or mousewheel), zoomed in to mag1

## Expected Behavior
The yz, xz viewports and 3d viewport should show in which direction the move was taking place

## Current Behavior
Those viewports do not visibly change

## Steps to Reproduce the bug
Viewing a dataset, toggling between two adjacent slices (either by alternating d/f or mousewheel), zoomed in to mag1

## Your Environment for bug
Firefox 86 Windows 10

## Note
https://github.com/scalableminds/webknossos/pull/5201 probably causes this. Philipp already explained that to solve this while keeping the desired behavior from there, the code would have to differentiate between holding keys pressed and hitting them singly. Let’s see if other users complain about this. If it’s just me, the priority is not high.

**Comment by philippotto** [comment]
I gave this issue some thought and after a good night's sleep, I think, that I have found a solution that should satisfy all requirements:

- The initial movement (let's say `f`) will always increase the respective coordinate by one. this is equivalent to the old behavior, we had. Thus, the next integer is always reached on initial movement and there's a visible change in viewport.
-  When keeping f held, the initial delay is adapted so that the expected delay+speed is met (depends on the decimal value of the current coordinate)
  - e.g., the user has configured a delay of 200ms and a speed of 2 slices/second (== 500ms/slice)
  - Scenario 1: z=10. The initial f press will set z to 11 immediately. Afterwards, a delay of 200ms is waited before continuing to increase z so that 2 slices/second are visited. --> after 700ms, z=12 will be reached.
  - Scenario 2: z=10.9. The initial f will set to 11.9 immediately. Afterwards, a delay of 700ms is waited before continuing to increase z. --> After 700ms, z=12 will be reached.


Does this make sense? The only (very minor) downside I see is that the "delay for continuous movement in the secondary viewports" will feel different. However, the speed and delay in the active viewport will always match the user's configuration.
