### ISSUE TITLE
Deactivate "Center new nodes" doesn't work in merger mode and when deleting

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5398]
## Context
Not centering nodes upon creating is great.

## Expected Behavior
- Should work in Merger Mode
- Should not move to active node, when deleting a node

## Current Behavior
https://user-images.githubusercontent.com/335438/114854745-6f946580-9de5-11eb-9fbf-0d500c51095e.mp4

## Steps to Reproduce the bug
1. Open an annotation
2. Deactivate center new nodes
3. Create some nodes, delete some nodes
3. Start Merger Mode
4. Create some nodes, delete some nodes

**Comment by philippotto** [comment]
Strictly speaking, the setting's name is "center **new** nodes" which means that it shouldn't really alter the behavior when deleting a node. But I see that it could be more intuitive if the setting covers both cases. We would need another name then. "Center active node" wouldn't work, since I'd still want to select the active node when selecting another tree..

I'll have a look at the merger-mode part of this issue, since that seems like to be an actual bug.

**Comment by philippotto** [comment]
Ok, I changed the delete-behavior, too. See https://github.com/scalableminds/webknossos/pull/5538. Still looking for a nice name for the setting, though. Maybe just "Center Active Node". It's a bit unspecific, but maybe alright :thinking:
