### ISSUE TITLE
Mappings overwrite volume annotation buckets

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5427]
## Context
Created a Hybrid annotation on a Dataset with segmentation layer and agglomerate mapping. Brushed, then selected different agglomerate mapping

## Expected Behavior
Brushed-on buckets should not be changed

## Current Behavior
Brushed-on buckets vanish, mapped segmentation data is displayed instead

## Steps to Reproduce the bug
See Context

## Your Environment for bug
Firefox 88 Linux, current wk master

## Related:
#5415 and #4796

**Comment by philippotto** [comment]
Also see https://github.com/scalableminds/webknossos/issues/5431

**Comment by philippotto** [comment]
I think, in our workshop discussions we basically agreed on "pinning" the active mapping once a brushing stroke was done. Since this information would also provide the info whether the user brushed at all, we could use that in other places, too (e.g., if the user never brushed, there's no sense in requesting buckets from that volume layer).

**Comment by fm3** [comment]
fixed by #7549
