### ISSUE TITLE
Clicking view button too soon after completed conversion job leads to non-imported dataset

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5467]
WKW import job in long running job list was shown as successful, I clicked “view”, but the dataset was not available yet. We should trigger the reporting of this dataset when the conversion is done. Maybe the worker could trigger the datastore reporting API similar to what voxelytics does.

**Comment by philippotto** [comment]
Similarly, I also experienced that vx generated a wk link (during publish), but the link pointed to "nowhere", since the DS wasn't found yet. Two things come to my mind here:

- (1) when showing the error message, render a "retry" button which scans the disk for the requested dataset name
- (2) do (1) automatically?

**Comment by philippotto** [comment]
Ah, interesting. Then, it was probably a race condition. vx prints the url *before* the import is triggered apparently: https://github.com/scalableminds/voxelytics/blob/09d7c22bfec4c07c7fba0d3359848c29cc75440d/voxelytics/align/tools/publish_dataset.py#L123

**Comment by fm3** [comment]
Fixed it in vx too :) https://github.com/scalableminds/voxelytics/pull/2441
