### ISSUE TITLE
Disable viewport click interactions while context menu is open

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5606]
When I want to close the viewport context menu without selecting one of its options, I click on an empty area near it. This currently creates a node / brushes at that spot. I’d argue that this click should instead _only_ close the context menu, and only after that, the viewport click interactions should be enabled again. That would mirror the behavior of the browser context menu

**Comment by MichaelBuessemeyer** [comment]
>I’d argue that this click should instead only close the context menu, and only after that, the viewport click interactions should be enabled again.

I also think that would make sense :computer_mouse:

**Comment by philippotto** [comment]
Regarding the implementation:

When I was working on the related PR, I tried to implement this, but it turned out to be a bit complicated, since it collides somewhat with the requirement that a repeated rightclick should open the context menu again at another place. Before that, we simply had a dummy div over the entire screen which consumed the left/right click and closed the context menu. However, in order to have the right click open the menu again, we cannot use the dummy div, as that div has no information about how the context menu should be opened (for that action, several internal objects are needed).

An alternative solution would be to make all click handlers aware of the fact whether the context menu is currently open. If this is the case, all handlers could default to a no-op. This is probably easier to do.

**Comment by fm3** [comment]
Why does a repeated right click have to open another context menu immediately? I just tried out a few tools and found that the second right click does nothing but close the first context menu. But if this is a requirement, I agree that your approach sounds reasonable

**Comment by philippotto** [comment]
Yeah, maybe it's not a hard requirement. It was at least mentioned in a feedback round: https://scm.slack.com/archives/C5AKLAV0B/p1621430168022400?thread_ts=1621422965.012900&cid=C5AKLAV0B

However, ditching that requirement is probably better than the status quo :shrug:
