### ISSUE TITLE
Moving while saving initiates too many save requests

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5681]
## Context
When saving an annotation, one can provoke countless save requests by simply moving continuously through the dataset.

## Expected Behavior
Batching subsequent move actions should still be batched.

## Current Behavior
For each move action, there will be a save request.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. move through an annotation with "f" for 60s
2. after 30s the saving should start and with that, the countless save requests will be triggered

## Your Environment for bug
chrome/linux

## Details
The culprit is at: https://github.com/scalableminds/webknossos/blob/a5fafe017ba9de00f8d9bf0fd8b8ab2830587b8c/frontend/javascripts/oxalis/model/sagas/save_saga.js#L404-L404

The logic here is intuitive, but leads to the behavior explained above. I think, we should only drain the save queue if the user explicitly clicked "Save" (i.e., the `SAVE_NOW` action was dispatched). In that case, the user expects the spinner to step in the next seconds. For the auto-save, it's fine to simply empty the save-queue and ignore new items added to it afterwards.

**Comment by MichaelBuessemeyer** [comment]
> The logic here is intuitive, but leads to the behavior explained above. I think, we should only drain the save queue if the user explicitly clicked "Save" (i.e., the SAVE_NOW action was dispatched). In that case, the user expects the spinner to step in the next seconds. For the auto-save, it's fine to simply empty the save-queue and ignore new items added to it afterwards.

@philippotto Could you please explain what you mean with your proposed idea?
 I think I do not understand your idea completely. It sounds to me like you want the user to opt in on saving the tracing and do not want the auto save functionality anymore.
I guess what you mean is to ignore all position updates and not send them to the backend as long as the queue only contains position updates? Because imo this does not solve the problem. If the user moved a lot through the dataset the last 30 secs and in the middle of the time once added a new tracing node to a tree, the movement after creating the new node would still be send to the backend. At least that's how understand your idea. 

My way of solving this would be to only send the newest position update action to the backend. The previous position updates would be deleted / forget by the save queue. Thus the update would only include relevant actions like creating a new node or changing the active segment together with only the lastest position in the tracing.

**Comment by philippotto** [comment]
> It sounds to me like you want the user to opt in on saving the tracing and do not want the auto save functionality anymore.
I guess what you mean is to ignore all position updates and not send them to the backend as long as the queue only contains position updates?

Hmm, I probably haven't described my suggestion very well then. Let me try to put it differently (but let's jump on a call, if it's still confusing):

The current save mechanism can be triggered by two events: a) auto-saving after 30s have passed or b) the user clicked "Save". In both cases, the save mechanism currently tries to reach a state of "everything is saved now and there is nothing new to be saved" (this is the while loop linked in the issue description). This "drainage" makes sense for event (b) since the user expects wk to be fully saved afterwards. However, in case of (a) it doesn't really make much sense in my opinion. The prime example for this is when I'm continuously moving across the dataset. As long as I'm moving, wk would try to save the newest event (effectively canceling the compaction of update actions as each action is saved individually). Therefore, I wouldn't do the "drainage" in scenario (a). It should be enough to save everything from the save queue which existed at the moment when event (a) occured.
Does this make sense?

> My way of solving this would be to only send the newest position update action to the backend. The previous position updates would be deleted / forget by the save queue. Thus the update would only include relevant actions like creating a new node or changing the active segment together with only the lastest position in the tracing.

I think, this would be additional complexity which can be avoided, since we already have compaction mechanisms in place. I think, my above suggestion should be very simple to implement, too (i.e., only do the while-loop `if (user initiated save manually)`.

Let me know if things got clearer now. Also it might be that I'm missing something here :)
