### ISSUE TITLE
Reload layer in incognito fails

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5734]
## Expected Behavior
Probably, the button shouldn't be available for non-authorized users.

## Current Behavior
It fails with unhelpful error messages.
<img width="1595" alt="Screenshot 2021-09-17 at 16 19 46" src="https://user-images.githubusercontent.com/335438/133798731-ee3f80cc-bdcc-485e-a248-418305bbde5d.png">

## Steps to Reproduce the bug
I was clicking the "reload" button on the color layer in this dataset: https://webknossos.org/datasets/scalable_minds/l4dense_motta_et_al_demo/view

**Comment by fm3** [comment]
Came across this again. Since the button clears the caches on the server, this action currently considered “administration” of the dataset, not “read”. We could now

(1) Allow this for any user, since it cannot do much harm, except cause extra load and decrease perf for all
(2) Soften the behavior of the button in the front-end, if the user does not have administration right for the dataset, to only reload the data from the backend, but not call the clear-caches route
(3) Hide the button entirely if the user does not have administration rights for the dataset

Any opinions? cc @philippotto

**Comment by philippotto** [comment]
Hm, initially, I was about to say (2), but I'm not really sure what the use case for unauthorized users is in general. They probably didn't change the dataset on the server. Therefore, (3) seems reasonable to me.

Alternatively, one could do (1) and combine it with a back-end sleep of a few seconds to do some cheapo rate limiting. However, I still don't really see a good use case for unregistered users. So, let's do (3) if nobody disagrees.
