### ISSUE TITLE
Make agglomerate skeleton loading feature available via context menu

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#5762]
## Detailed Description

Make the "Shift + Middleclick" feature to load agglomerate skeletons also available via the context menu.

## Context

Would be a great improvement for the usability of the feature as the `Shift + Middleclick` shortcut is not discoverable and the button in the segmentation layer setting can only be used to load the centered agglomerate.

**Comment by philippotto** [comment]
@Dagobert42 The relevant code parts are these:

https://github.com/scalableminds/webknossos/blob/ed0c278efb1fdd64d4bcd0b1427243af87b48b47/frontend/javascripts/oxalis/controller/combinations/tool_controls.js#L261-L261
https://github.com/scalableminds/webknossos/blob/ed0c278efb1fdd64d4bcd0b1427243af87b48b47/frontend/javascripts/oxalis/view/context_menu.js#L558-L558

The upper code is where the "shift + middleclick" handler is currently implemented. It can be removed and instead the functionality should appear in the context menu (see how that is populated in the second link). Since the context menu already 
knows the `globalPosition` you can directly call `loadAgglomerateSkeletonAtPosition(globalPosition)`.

As a final tweak, you could make sure to only show the entry in the context menu if the action makes sense at all (e.g., an agglomerate mapping is defined). For this, you can simply re-use this code within `loadAgglomerateSkeletonAtPosition`:

```
const { mappingName, mappingType, isMappingEnabled } = getMappingInfo(
    state.temporaryConfiguration.activeMappingByLayer,
    segmentation.name,
  );
  if (mappingName == null || !isMappingEnabled) {
    Toast.error(messages["tracing.agglomerate_skeleton.no_mapping"]);
    return;
  }
  if (mappingType !== "HDF5") {
    Toast.error(messages["tracing.agglomerate_skeleton.no_agglomerate_file"]);
    return;
  }
```

Ideally, extract this into a helper function so that the code is not duplicated.

To test this feature you will need a dataset with an agglomerate file. You can download it from [here](https://www.notion.so/scalableminds/Test-Data-c0563be9c4a4499dae4e16d9b2497cfb#4f27c86bc8fc485e9d04b0dc1b1488c9) and need to extract the archive so that the folder `webknossos/binaryData/sample_organization/test-agglomerate-file` exists (which then includes `datasource-properties.json` for example).

If you click on "Refresh" in http://localhost:9000/dashboard/datasets, the dataset should appear in the list. Then click "New annotation" for the dataset. In the wk core view, activate "ID mapping" in the left sidebar. Then, you can select "agglomerate_view_70". If you select the "skeleton" tool in the top toolbar and use "shift + middleclick" on a colored segment, a new skeleton should appear :crossed_fingers: 

![image](https://user-images.githubusercontent.com/2486553/145578265-75b3a8fb-fbfa-4e9b-a388-399e84cd7f5e.png)

![image](https://user-images.githubusercontent.com/2486553/145578478-450d0ac9-c7ad-44b0-aa37-e1fb4cd73672.png)


As always, please let me know if you get stuck :) It would also make sense to give you a proper introduction about what mappings and agglomerates views are at all, but it's easier to do it in-person / per call. I hope this information here is enough for now to get started :rocket:
