### ISSUE TITLE
Dataset edit button is shown even to users who cannot edit the datast settings

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5791]
In the view mode (or annotation mode), in the info tab, next to the dataset name, an icon is shown that links to the dataset edit page. This should only be shown if the user can actually visit that edit page (i.e. is in the dataset’s organization and is dataset manager or admin)

Also, could we use a different icon (e.g. cogwheel)? The edit stylus icon is the same as for editing the annotation name, which is confusing to me

**Comment by philippotto** [comment]
@Dagobert42 the boolean check for whether the icon should be shown would probably look something like this:

`activeUser != null && activeUser.organization === dataset.owningOrganization && (activeUser.isAdmin || activeUser.isDatasetManager)`

Testing this might be a bit tedious to set up. We could have a call about this, since it requires some knowledge about setting up additional users, permissions of users and datasets etc.
