### ISSUE TITLE
Allow to assign a certain task to a certain user?

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5810]
## Detailed Description
After creating a task, should there be the functionality to assign the task to a certain user? This would be easier to understand than the current workflow (the user has to click "get task" and if they meet all the requirements :tm:  they get the task).

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
I’d say the easiest way to implement this is to add a route that creates a task annotation for the assignee user. The state this results in is identical to what happens when users “self-assign” a task via the get new task button. It shows up in their dashboard automatically. Do you think this is sufficient? Or should there be a different concept of assignees (where the user still has to request the task?)

**Comment by philippotto** [comment]
> I’d say the easiest way to implement this is to add a route that creates a task annotation for the assignee user. The state this results in is identical to what happens when users “self-assign” a task via the get new task button. It shows up in their dashboard automatically. Do you think this is sufficient? Or should there be a different concept of assignees (where the user still has to request the task?)

Sorry for the late reply. Makes perfect sense to me! I assume this is also how you built it now in #6528, right?
