### ISSUE TITLE
Remove requirement of largestSegmentId

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#6039]
webKnossos currently requires a `largestSegmentId > 0` to be set for each segmentation layer. This was meant to force the user to set the value in order to be able to do volume annotations without re-using existing segment ids. However, often this largest id is not known to the user and the requirement becomes a nuisance and guesses are used. With multiple volume annotation layers, it is now possible to add annotations without overwriting any data.
Also, the `largestSegmentId` of a segmentation layer can be `0` when completely empty. Although, it would be practical to leave out the layer entirely, we shouldn't consider it invalid state.

I propose to allow `0` for `largestSegmentId` and to make the field optional.
Opinions? @fm3 @philippotto

**Comment by philippotto** [comment]
I agree, that `0` should be a valid value for an empty segmentation layer (even though, it will be rare). However, what would be the semantics when the largest segment id is omitted? `0` too? This sounds dangerous to me (as in: can cause hard to find and hard to fix segmentation bugs). I agree that the current usability is quite poor, but I'd rather solve it by automatically scanning segmentation layers for the largest segment id (for example). Also, one could defer the question for the largest segment id for when the user really wants to annotate with the fallback layer. Then, one could ask the user what to do (e.g., let them fill it out manually, let them trigger a scan for the largest id etc).

> With multiple volume annotation layers, it is now possible to add annotations without overwriting any data.

I consider editing/correcting an existing segmentation layer still an important use case for which one would likely use the fallback functionality (as one cannot remove segments, otherwise). If the user corrects segments and brushes with ids which already exist somewhere trouble is bound to happen.

**Comment by fm3** [comment]
I agree with Philipp that annotating with fallback layer is not completely replaced by the multiple annotation layers. Because of this I too am uncertain whether simply removing the requirement is a good idea. Deferring it until you actually create the first volume annotation with fallback layer might make sense (but the user who is allowed to edit the dataset metadata is not necessarily the same user who wants to annotate it, so they might be blocked then…)

**Comment by normanrz** [comment]
How about a `null` value for `largestSegmentId`, which would indicate `unset`. I think it is very important to make the `largestSegmentId` optional upon import/upload. This is just a barrier for users to try out webKnossos.

We can add a feature to the frontend to add the `largestSegmentId` when we actually need it. That would be when starting to paint some data on a new segment. The modal could also suggest to add a separate layer to not overwrite existing segmentations. We can also add a long-running job to calculate the max id.

**Comment by philippotto** [comment]
Since this is basically what I also suggested above, I'm all for it :smile:

**Comment by normanrz** [comment]
True :D
This will also need to be implemented in the libs @jstriebel

**Comment by fm3** [comment]
Sounds fair to me. So this modal would have to pop up when the user wants to take the very first brush stroke in a volume layer with fallback segmentation, right?
This would set the largestSegmentId for that volume layer, and would also give a hint to the user that a dataset manager can set it in the datast settings or start a long-running job to extract the true id from the data.
