### ISSUE TITLE
Annotating an anisotropic dataset with volume resolution restrictions behaves incorrectly

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#6138]
## Context

This bug occured during volume annotation on an anisotropic dataset with resolutions 1-1-1 and 2-2-1. Volume annotation was restricted to resolution 2-2-1.

## Expected Behavior

Only the z-slice that was annotated should be annotated, both in mag 1-1-1 and 2-2-1.

## Current Behavior

If brushing in mag 1-1-1, the next slice is mistakenly annotated as well. In mag 2-2-1, the next slice is not annotated (as expected).
If brushing in mag 2-2-1, only a single slice is annotated in mag 2-2-1 (as expected). However, in mag 1-1-1, the previous slice is annotated as well.

## Steps to Reproduce the bug

1. Create a hybrid annotation on an anisotropic dataset (with mags 1-1-1 and 2-2-1) and restrict the volume resolution to disallow annotation in mag 1-1-1
2. Use the brush to annotate in mag 1-1-1 -> The next slice is mistakenly annotated as well. In mag 2-2-1, the next slice is not annotated.
3. Also, use the brush to annotate in mag 2-2-1 -> In mag 1-1-1, the previous slice is annotated as well.

## Your Environment for bug

- Version of WebKnossos (Release or Commit): 22.04.0

**Comment by philippotto** [comment]
Note that there is a bug in the fallback rendering code which can lead to confusion about which mag was actually labeled. Disable fallback rendering to ensure that it doesn't interfere with debugging the actual issue. Also see #6029.

**Comment by philippotto** [comment]
> Note that there is a bug in the fallback rendering code which can lead to confusion about which mag was actually labeled. Disable fallback rendering to ensure that it doesn't interfere with debugging the actual issue. Also see #6029.

After a good night's sleep, I think, the "actual issue" doesn't really exist. Disabling fallback rendering makes this bug report not reproducible for me (in fact, I can toggle between the best-quality-first and progressive-quality setting to make the bug appear/disappear).

However, the issue itself is a good way to provoke the fallback-rendering bug (due to the restriction, "permanent" fallback rendering is enforced which makes the bug visible; otherwise, the bug would only be briefly visible while buckets are still loading). Therefore, I'd say, we keep this issue open.
