### ISSUE TITLE
mapping and other parameters for zarr streaming

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#6193]
Currently, applying back-end side mappings is only possible for the wk data request. The other two ways of requesting raw data (GET raw and zarr) should also support this.

**Comment by fm3** [comment]
It is unclear how the zarr URI schema should be adapted for this. Adding discussion label.

**Comment by normanrz** [comment]
> It is unclear how the zarr URI schema should be adapted for this. Adding discussion label.

I was thinking of using query params for that. However, I discussed that in the zarr gitter. The strong recommendation was to use separate URLs (i.e. datasets) for that. 

I don't know how that could fit our URL scheme. A few ideas:
```
GET /data/zarr/scalable_minds/l4_sample/segmentation/with_mapping_agglomerate_60
GET /data/zarr/scalable_minds/l4_sample/segmentation__mapping=agglomerate_60
GET /data/zarr/scalable_minds/l4_sample/segmentation:mapping=agglomerate_60
GET /data/zarr/scalable_minds/l4_sample/segmentation:mapping=agglomerate_60&only_segment=12312
```

**Comment by fm3** [comment]
Using special characters like : and = means they can not then be used in a normal dataset name. Is there a reason not to use / (which is already a special character)?

`GET /data/zarr/scalable_minds/l4_sample/segmentation/withMapping/agglomerate_60/2-2-1/.zarray`

**Comment by normanrz** [comment]
On a similar note, I think we also need to think about a way to input the token as part of the path. This will allow it to view private datasets and annotations in other tools. I haven't seen one that would implement an authentication UI to input anything.

**Comment by leowe** [comment]
@normanrz On what does the decision how `zarr` handles the parameters depend? Is this still an open question in the spec?

**Comment by normanrz** [comment]
The decision depends on us sitting down and thinking it through properly :-) I think the implementation needs to wait until then.

**Comment by normanrz** [comment]
Summarizing today's discussion:
- Focus on making private (token-protected) annotations available through zarr. Private datasets can easily be shared, by creating an empty annotation. The mapping can also be set in the annotation.
- Add new database-backed links ("access links") for providing authenticated access to these resources. The database items contain annotation id, expiration date, and maybe additional fields.
- Access to these annotations will be available through the datastores, because they will likely contain the heaviest data (e.g. color data, full segmentation)
- Routes could be in the form of `https://datastore/data/zarr_private/:accessId/:dataLayerName/...`.
- The datastore will then need to perform RPC calls to webknossos and tracingstore in order to fetch information about the dataset/layers and annotation data.
- There needs to be routes to create, list (per annotation) and delete these access links.
