### ISSUE TITLE
Find (shortest) path between two super voxels

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6267]
Related to #6265, finding the shortest path between two super voxels could be a useful tool. This could be a precursor to an actual min-cut approach. It's not totally clear whether both is needed.

**Comment by normanrz** [comment]
The UX that I imagine for splitting agglomerates:
- User clicks on 2 positions in an agglomerate
- Frontend sends the coordinates to the backend
- Backend resolves the coordinates to segments (return error if same segment) and computes the paths between the 2 segments given the agglomerate graph
- Frontend displays this path in UI
- User removes an edge from the path, which results in a split operation that is sent to the backend
- Split complete

Open questions:
- Should the backend return multiple (or all) paths instead of a single (e.g. shortest) path?

**Comment by fm3** [comment]
unassigning us for the moment as we decided to schedule this issue later, also pending more user feedback, and instead first tackle #6265 min-cut, compare discussion at https://scm.slack.com/archives/C5AKLAV0B/p1656669422893109?thread_ts=1656657919.713259&cid=C5AKLAV0B

**Comment by hotzenklotz** [comment]
@philippotto Is this still relevant? I though we just release a feature "Extract shortest path to this node"? Or is the issue meant to find the path without agglomerate skeletons?

**Comment by philippotto** [comment]
We have:
- extract shortest path (for pure skeletons)
- min-cut an agglomerate skeleton

The latter is closely related to the initial idea of this issue and probably the better mechanism. Therefore, I'm closing this issue now.
