### ISSUE TITLE
Allow import of remote Zarr datasets

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#6272]
We need a UI to import remote Zarr datasets. Users should be able to enter URLs to their datasets. I imaging that there is a backend route that takes the URL and classifies what kind of data is present, e.g.:
- webKnossos-style dataset (with datasource-properties.json) -> Dataset
- OME-Zarr layer (has .zattrs with OME-NGFF metadata) -> Layer
- Multi-layer OME-Zarr (has .zgroup and OME-layers as sub paths) -> Dataset
- Zarr array (just a zarr array with .zarray) -> Layer

In case of a detected dataset, the user could import that right away. In case of layers, the user may want to add additional layers (i.e. same procedure) before final import.

Supported schemes are http(s), s3, gcs. There should be UI for adding credentials specific to each of these schemes (http => basic or bearer auth, s3 => access key id+secret key, gcs => credentials json (already present for neuroglancer import)).

I don't have a strong opinion, how the datasets are then stored. One idea that @fm3 (please comment) mentioned, was to put a folder with datasoure-properties.json on a datastore.

**Comment by normanrz** [comment]
Here is a quick UI mockup:
![zarr-import](https://user-images.githubusercontent.com/335438/173042638-91f6ac3a-8fd4-454d-9645-e2bcd055bde0.png)

**Comment by leowe** [comment]
The general idea here but would still be that to view the data, it has to be imported, i.e. saved to webknossos server as a "normal" dataset. Do I understand that correctly?

**Comment by fm3** [comment]
Correct. What exactly this “imported“ means is up for debate. The current implementation would require a datasource-properties.json being written and placed on a datastore filesystem. And I’d say this is what we should go with for the first version. However, this may change in the future. For example, it may be sufficient to store the information in postgres, rather than in a json file. (If the actual data is streamed from remote anyway, there is no real need to involve a local file system)
