### ISSUE TITLE
Inconsistent call order of hooks in context menu

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#6814]
## Context

There seems to be an error in the order of hook calls in the context menu. 
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/39529669/216655031-4bf21223-1db7-48a0-909e-0376b29ba162.png">

I think this causes the following behavior:
See below in the issue
## Expected Behavior

There should not be an error in the hook order. Moreover, opening the context menu in any viewport when a different viewport has been active, should result in all menu items being displayed and not an empty menu.
## Current Behavior

see above / below
## Steps to Reproduce the bug

1. Open a hybrid tracing
2. create a skeleton with some nodes
3. move the mouse into the 3d viewport without clicking and there hover a node of the skeleton you just created
4. right click to open the menu. The menu should be empty. Reopening the menu on the skeleton node should now show the skeleton actions.

## Your Environment for bug

- Browser name and version: e.g. Chrome
- Operating System and version: e.g. Mac OS 12´

**Comment by MichaelBuessemeyer** [comment]
I think I found the commit / changes that introduced this error: https://github.com/scalableminds/webknossos/pull/6591/files#r1096000387
in pr #6591.

@philippotto As far as I can read it, you made the changes. What was the reason to switch to a `ContextMenuContext.Provider` and do you maybe know the cause for this bug or have a hunch? 🤔

**Comment by philippotto** [comment]
> @philippotto As far as I can read it, you made the changes. What was the reason to switch to a `ContextMenuContext.Provider` and do you maybe know the cause for this bug or have a hunch?

I think (not sure though) the issue already existed before my latest changes in that code area. I think this code here is responsible for the error: https://github.com/scalableminds/webknossos/blob/master/frontend/javascripts/oxalis/view/context_menu.tsx#L1115-L1133

In the linked snippet two react components are used without using JSX syntax (due to reasons explained in the code comment). Due to that hack, the rules-of-hooks are violated without the linter being able to notice this.

Therefore, I assume it would be best to remove the workaround to solve the original problem.

**Comment by MichaelBuessemeyer** [comment]
> In the linked snippet two react components are used without using JSX syntax (due to reasons explained in the code comment). Due to that hack, the rules-of-hooks are violated without the linter being able to notice this.

Therefore, I assume it would be best to remove the workaround to solve the original problem.

Oh 🤯, that actually sounds like a very reason for this bug. Thanks for having a look :)
