### ISSUE TITLE
multislice tif upload

### ISSUE THREAD

**Issue by boergens** [scalableminds/webknossos#6846]
It would be great if webKnossos would support the import of multislice tiff datasets.
Normally I wouldn't think it's that important but the problem is that wK currently happily spends hours uploading a huge multislice tiff and then only displays the first slice -- and that feels a bit anticlimactic

**Comment by fm3** [comment]
Hi and thanks for your report! This is supposed to work already, could you supply a link to the converted dataset? We can have a look at what happened during the conversion.

**Comment by boergens** [comment]
Hi,
I deleted it but maybe you can still access it?
Sample40_488_221219_MTG6_rball30px	2023-02-10 01:56

**Comment by fm3** [comment]
Hi @boergens 
we managed to convert the dataset, please find it under the name `Sample40_488_221219_MTG6_rball30px_reconvert`.

There are different kind of multislice tif formats. Your image seems to use a non-standard tiff extension introduced by ImageJ.
Neither imagemagick nor python tifffile nor gimp recognize it. Still we agree that WEBKNOSSOS should be able to auto-detect that and use the correct conversion. This is now tracked in issue https://github.com/scalableminds/webknossos-libs/issues/870

In the meantime, you can use the following python script to convert imageJ hyperstacks like this one to wkw, which can then be uploaded to webKnossos:

```
import webknossos as wk
from cluster_tools import WrappedProcessPoolExecutor
import numpy as np

def main():
    ds = wk.Dataset("/path/to/write/to", voxel_size=(1,1,1))

    layer = out_ds.add_layer_from_images(
        images="/path/to/directory/containing/the/tif",
        layer_name="color",
        executor=WrappedProcessPoolExecutor(max_workers=6),
        use_bioformats=True,
        dtype=np.uint16
    )
    ds.downsample(executor=WrappedProcessPoolExecutor(max_workers=6))

if __name__ == '__main__':
    main()
```

The relevant line being `use_bioformats=True`. This uses a java conversion, which knows about the imageJ format, instead of the default tiff conversion.

I hope that works for you until we can solve https://github.com/scalableminds/webknossos-libs/issues/870

**Comment by boergens** [comment]
Awesome, thanks so much!
