### ISSUE TITLE
Some segment actions are not properly disabled for non-editable segmentation layers

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7207]
## Context
Annotation for a dataset with a segmentation layer, but where the segmentation layer is not editable.
https://scm.slack.com/archives/C5AKLAV0B/p1689585308901369?thread_ts=1688991494.182429&cid=C5AKLAV0B

## Expected Behavior
- "create new group" should be disabled
- user should not be able to rename segments

## Current Behavior
- create new group can be clicked but nothing happens
- segments can be renamed (on reload, this change will be lost)

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. create annotation for a dataset that has a segmentation layer but don't create an editable segmentation layer (e.g., only skeleton annotation layer or create a new/empty segmentation layer)
2. make sure the non-empty segmentation layer is visible
3. click on some segments to fill the segment list
4. use context menu on the root group and try to rename segments

**Comment by dieknolle3333** [comment]
In this list of single segment actions: 
![Image](https://github.com/scalableminds/webknossos/assets/57364771/49498494-6de7-4930-836c-ba8ff6c09265) 
and this list of segment group actions: 
![Image](https://github.com/scalableminds/webknossos/assets/57364771/efe69658-7b08-4387-be68-57a58819624b)
I am assuming that the only actions that should be possible for visible but uneditable segmentation layers are `Remove segment from list` and `Load meshes (precomputed)` in case there is a meshfile, right? Because everything else would be editing the segmentation layer. 
Do you agree or did I misunderstand something?

**Comment by dieknolle3333** [comment]
see more details here: https://scm.slack.com/archives/C5AKLAV0B/p1694797660535889
