### ISSUE TITLE
Iterate on UI for AI features

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7268]
## Detailed Description
WK (with jobsEnabled=true) allows to start certain processing jobs that use AI (for example, nuclei and neuron segmentation). The UI should be improved to make it easier to explore, to understand and to start such jobs. Creating mock-ups for that UI (and comparing them to the existing UI) could be a first step for that.

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by Albane-dlv** [comment]
![UI for AI features](https://github.com/scalableminds/webknossos/assets/83946334/aca17218-c88e-4f6c-a036-0c7be62592c8)

Use the mockup (attached) as a reference and then build with the standard Antd components as closely as possible.

**Comment by Albane-dlv** [comment]
Thumbnails for the different processing jobs. 
![thumbnail mitos](https://github.com/scalableminds/webknossos/assets/83946334/b07a3f42-1897-43b5-9a23-7876b855a372)
![thumbnail neuron segmentation](https://github.com/scalableminds/webknossos/assets/83946334/0ed66291-7f2f-4d77-8aef-dd753052a927)
![thumbnail nuclei](https://github.com/scalableminds/webknossos/assets/83946334/06512b3a-f7de-4b3c-bccc-cf96d59399a0)

**Comment by dieknolle3333** [comment]
@Albane-dlv I dont think that we are already using a warning icon like above, are we? (yellow borders, black exclamation mark.) could you provide me with a right image for this?
otherwise I would use antd's [Alert](https://4x.ant.design/components/alert/) (see below), but I dont think thats ideal. 
<img width="656" alt="Screenshot 2023-10-02 at 15 47 19" src="https://github.com/scalableminds/webknossos/assets/57364771/6edfb207-00c1-48a9-af7e-b83b3d8920cf">
