### ISSUE TITLE
Define Content Security Policy

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7345]
See https://github.com/scalableminds/webknossos/pull/7335 for context. We will split-off the CSP part into a separate PR, though.

Known problems for a strict CSP are:
- [ ] google analytics (maybe import a package from NPM instead of using a script-tag?)
- [ ] olvy (check-in their script; see https://github.com/scalableminds/webknossos/pull/7335/commits/63a68257072148a26cb80945950b7ffb4001c679)
- [ ] webpack sourcemaps (these use eval; maybe something like [this](https://github.com/webpack/webpack/issues/5627#issuecomment-374386048) helps, but it should be thoroughly tested, since I remember source map problems in the past with different modes)
- [ ] inline script in main.scala.html (potentially fixable with a hash)

Also test:
- [ ] sandbox mode in combination with connectome viewer

**Comment by daniel-wer** [comment]
I took over https://github.com/scalableminds/webknossos/pull/7367 from @MichaelBuessemeyer.
The CSP also limits which endpoints can be fetched ([connect-src](https://content-security-policy.com/connect-src/)). Since there are standalone tracing- and datastores, these will need to be whitelisted on a per-deployment basis. Additionally, we had to whitelist api.github.com and gist.github.com to allow the user script feature to continue working. Can you think of other endpoints that need to be whitelisted? 

Also, more importantly, I'm wondering about the remote dataset import. Isn't it true that any URL can be specified there? If so, I'm not sure how to make this work with the CSP or are all request to the specified URL performed by the backend?

**Comment by daniel-wer** [comment]
> I assume loading static assets (such as images) from another origin is okay, right? Can't think of more endpoints right now, but I guess we'll see..

Images are also restricted via https://content-security-policy.com/img-src/
Currently, this is configured to be `img-src 'self' data:`. Do you have other sources in mind?

**Comment by philippotto** [comment]
> Images are also restricted via https://content-security-policy.com/img-src/
> Currently, this is configured to be `img-src 'self' data:`. Do you have other sources in mind?

I had the organization logo in mind, but I think we don't render that anymore (at least, I didnt find it). Also, I searched for `src="http` which didn't yield any matches. So, it's probably okay :)
