### ISSUE TITLE
The development environment cannot upload datasets.

### ISSUE THREAD

**Issue by GanLab123** [scalableminds/webknossos#7508]
## Context
I followed the steps in DEV_INSTALL.md but couldn't upload the dataset. Is there anything else I need to do?
## Expected Behavior
Successfully uploaded the dataset
## Current Behavior
When uploading the dataset, it shows that the datastore server is not available.
## Steps to Reproduce the bug
The error is easy to reproduce.

1.Follow the steps in DEV_INSTALL.md
2.Upload dataset
![image](https://github.com/scalableminds/webknossos/assets/83834702/479304f6-1e44-47bb-b187-b264e8a15a9c)
because other services are using port 9000, I have changed all instances of '9000' in the code to '19000'
![image](https://github.com/scalableminds/webknossos/assets/83834702/897dc0d0-87e2-4164-8b25-f1c1ca018d53)

When I manually create a directory named 'binaryData' in the webknossos directory:
![image](https://github.com/scalableminds/webknossos/assets/83834702/3d4b0c31-70d0-4966-9fb5-edac6ee59a55)

## Your Environment for bug
- Browser name and version: Chrome 39
- Operating System and version: Ubuntu 20.04.6
- Version of WEBKNOSSOS (23.11.0):

**Comment by fm3** [comment]
Hi and thanks for your report! May I ask which variant from DEV_INSTALL you went for? Docker or manual installation? I assume manual, in order to be able to change the ports?

What happens when you visit localhost:19000/data/health in your browser?

The logging (after creating the binaryData directory) looks ok.

If the automatic creation of the binaryData directory failed, it may be that the organization directory also wasn’t created. I’d suggest to create a directory called `sample_organization` inside of the binaryData directory and try again. This is assuming that you used the default config, where `sample_organization` is the name of the organization created on startup. You can double-check this by visiting localhost:19000/api/organizations (while logged in)

Hope this helps!

**Comment by 913024733** [comment]
First of all, thank you for your response. I installed it manually. When I visit localhost:19000/data/health, it prompts ERR_CONNECTION_REFUSED. I created a folder named sample_organization and manually placed a dataset inside it via FTP. 
![image](https://github.com/scalableminds/webknossos/assets/83834702/58634a85-de83-4394-9559-3cddcd192d74)
Interestingly, WebKnossos can display this dataset, but I still can't upload datasets. 
![image](https://github.com/scalableminds/webknossos/assets/83834702/b9170843-ab6d-4a96-a55e-d5ca224271f1)
Viewing this dataset shows a completely black screen, and I'm unable to create annotations.
![image](https://github.com/scalableminds/webknossos/assets/83834702/909c8099-58ca-4ef9-bff4-6b2d652aa622)

![image](https://github.com/scalableminds/webknossos/assets/83834702/238e836c-1782-48eb-a122-97338ce36b90)

Here is a similar [issue](https://forum.image.sc/t/webknossos-on-premises-datastore-not-available-error/66234), but he installed it using Docker, while I installed it manually.

**Comment by GanLab123** [comment]
The issue has been resolved. [see the link](https://github.com/scalableminds/webknossos/issues/7513)
