### ISSUE TITLE
Tag selection of annotations does not work with single letter tags

### ISSUE THREAD

**Issue by erjel** [scalableminds/webknossos#7629]
## Context
I tried to tag a couple of annotations in the annotation dashboard as quickly as possible. I decided to just use a single letter "t". When I now select this tag, I still see all annotations in the dashboard

## Expected Behavior
I would expect that webknossos only shows the tagged annotations

## Current Behavior
Webknossos shows a strange subset of all annotations. I need at least 3 characters "ttt" to see only the tagged annotations.

## Your Environment for bug

- Browser name and version: Firefox 122.0.1 (64-bit)
- Operating System and version: Windows 10
- Version of WEBKNOSSOS (Release or Commit): 24.02.0
- [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment]
Thanks for your report! I can confirm that something is off with filtering annotations by tags.

It looks like the selected tag is just appended to the search query and even if something other than the tag matches that (e.g. the user name), the annotation is displayed. So for single-letter tags, most annotations probably match that, since the letter is contained somewhere.

We’ll have a look into how this tag filtering can be used to actually filter only by the tags.

cc @philippotto

**Comment by philippotto** [comment]
Thanks for the report! I opened a PR which will fix this.
