### ISSUE TITLE
Occasionally, dataset uploads get stuck at 100%

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#7930]
Received reports of dataset uploads in the browser getting stuck at 100%, but never showing the »processing uploaded files« step.

I couldn’t reproduce it. Maybe we can provoke it with large datasets/artificially bad internet connections/making the tab inactive for long periods/restarting the server during the upload/almost exceeding disk quota/???

**Comment by philippotto** [comment]
Actionables:
- [ ] use math.ceil instead of math.round when rendering progress
- [ ] list all compatible file extensions (see [here](https://github.com/scalableminds/webknossos-libs/blob/92a14bb90fe1262eb18903f6f9dbbb10132422ca/webknossos/webknossos/dataset/_utils/pims_images.py#L701))
- [ ] more logging in backend?
- [ ] starvation code in frontend (warn user and ask to retry?)
- [ ] implement `GET testChunks` in backend and adapt frontend so that a page refresh will survive uploads
  - [ ] frontend could ask backend if there are ongoing uploads. if yes, the form could be initialized with these values again (including the upload id). the user would probably need to drag the file again into the area.

**Comment by fm3** [comment]
We did not get any more reports of this after https://github.com/scalableminds/webknossos/pull/7932. I’d assume that the timeout was indeed the solution.

Also, #7931 now even allows to continue uploads after client/browser restart.

Closing this until new bug reports reach us.
